// A stand-in "Liked Songs" library (~1000 songs) so anyone can try the poem
// composer without connecting Spotify. Titles only get used as poem lines;
// demo mode can't save to a real account.

const SONGS = [
  // ---- from the original playlist poems ----
  ["I Guess I Just Feel Like", "John Mayer"],
  ["When You're Around", "Dune Rats"],
  ["This Is Home", "Cavetown"],
  ["Don't Look Down", "OneRepublic"],
  ["Jump", "Mac Miller"],
  ["Don't Walk Away", "Dom Kennedy"],
  ["Fly Me To The Moon", "Frank Sinatra"],
  ["We Can Dance", "Devin Wessels"],
  ["In The Stars", "Benson Boone"],
  ["We Can Watch the Day Grow Dark", "Glacis"],
  ["Love on the Ground", "Cannons"],
  ["Traffic In The Sky", "Jack Johnson"],
  ["Time", "Pink Floyd"],
  ["Will", "Maps & Atlases"],
  ["June", "Briston Maroney"],
  ["And Now", "tomemitsu"],
  ["July", "HUNNY"],
  ["As Long As The Wind Blows", "Jim & Jesse"],
  ["I'll Be", "Reba McEntire"],
  ["Lovin' You", "Minnie Riperton"],
  ["I Won't Let Go", "Rascal Flatts"],
  ["I Will Not Say Goodbye", "Danny Gokey"],
  ["I'll Still Be Loving You", "Restless Heart"],
  ["Until The Day I Die", "Soran"],
  ["Why Are Sundays So Depressing", "The Strokes"],
  ["It's Not Easy", "Ofege"],
  ["Real Life", "ear"],
  ["The Man in Me", "Bob Dylan"],
  ["Whatcha Gonna Do", "The Valdons"],
  ["Before the Sun", "Gregory Alan Isakov"],
  ["Life's Been Good", "Joe Walsh"],
  ["Warm Love", "Van Morrison"],
  ["Carry Me Away", "John Mayer"],
  ["Set Adrift On Memory Bliss", "P.M. Dawn"],
  ["These Days", "The Black Keys"],
  ["My Tears Are Becoming A Sea", "M83"],
  ["Fade Into A Dream", "LÉON"],
  ["Another Night", "Mac Miller"],
  ["Lost In The World", "Kanye West"],
  ["Seasons", "IYAMAH"],
  ["Change", "J. Cole"],
  ["So Do I", "Christy Moore"],
  ["Somebody Told Me", "The Killers"],
  ["Stay Here", "Gaho"],
  ["Right Here", "Dave B."],
  ["Everything Will Be Okay", "gny"],
  ["How Can I Love You?", "Yellow Days"],
  ["What's It All For?", "Yellow Days"],
  ["when will it stop raining?", "K.Kenz"],
  ["I Just Don't Know", "Lucas Benoit"],
  ["So life goes on", "Heo Hoy Kyung"],
  ["I Think I Love You", "Phora"],
  ["I Think I Like When It Rains", "WILLIS"],
  ["I Think...", "Bladee"],
  ["I'm Yours", "Jason Mraz"],
  ["Sometimes", "Goth Babe"],
  ["Like Real People Do", "Hozier"],
  ["I Wonder", "Kanye West"],
  ["Why", "Dominic Fike"],
  ["Why is the sky blue?", "Self-Isolation Jazz Artists"],
  ["Sometimes I Ignore You Too", "tobi lou"],
  ["But, Please", "ScholarMan"],
  ["Please", "jagger finn"],
  ["Can I Call You Tonight?", "Dayglow"],
  ["Believe Me", "Navos"],
  ["My Love Is True", "Sugar Minott"],
  ["As the World Caves In", "Sarah Cothran"],
  ["Forever & Always", "Zeph"],
  ["It's Me & You", "Tokyo Tea Room"],
  ["When I Dream", "San Cisco"],
  ["I Dream, I Dream", "Jermaine Jackson"],
  ["Size of the Moon", "Pinegrove"],
  ["You Know I'm No Good", "Amy Winehouse"],
  ["I Do Too", "Averie Bielski"],
  ["Hard To Explain", "The Strokes"],
  ["I Like The Way You Walk", "The Donkeys"],
  ["I Like The Way You Love Me", "Brenton Wood"],
  ["Guess I Always Knew", "Love Apple"],
  ["Early Morning Rain", "Cleveland Francis"],
  ["Sun Rays Like Stilts", "Tommy Guerrero"],
  ["Late July", "Zach Bryan"],
  ["Midnight", "Mapache"],
  ["You and I", "Washed Out"],
  ["Wherever You Go", "Beach House"],
  ["Give You My Lovin", "Mazzy Star"],
  ["Beautiful Girl", "INXS"],
  ["You And Me", "Penny & The Quarters"],
  ["Sweetest Thing on This Side of Heaven", "Papa Bear & His Cubs"],

  // ---- 60s / classic rock ----
  ["Here Comes the Sun", "The Beatles"],
  ["Let It Be", "The Beatles"],
  ["Blackbird", "The Beatles"],
  ["Yesterday", "The Beatles"],
  ["In My Life", "The Beatles"],
  ["Across the Universe", "The Beatles"],
  ["The Long and Winding Road", "The Beatles"],
  ["Two of Us", "The Beatles"],
  ["I Will", "The Beatles"],
  ["Something", "The Beatles"],
  ["Golden Slumbers", "The Beatles"],
  ["Good Night", "The Beatles"],
  ["The End", "The Beatles"],
  ["Tomorrow Never Knows", "The Beatles"],
  ["While My Guitar Gently Weeps", "The Beatles"],
  ["Hey Jude", "The Beatles"],
  ["Come Together", "The Beatles"],
  ["Wish You Were Here", "Pink Floyd"],
  ["Breathe", "Pink Floyd"],
  ["Us and Them", "Pink Floyd"],
  ["Shine On You Crazy Diamond", "Pink Floyd"],
  ["Comfortably Numb", "Pink Floyd"],
  ["Money", "Pink Floyd"],
  ["Ramble On", "Led Zeppelin"],
  ["Going to California", "Led Zeppelin"],
  ["Thank You", "Led Zeppelin"],
  ["That's the Way", "Led Zeppelin"],
  ["Stairway to Heaven", "Led Zeppelin"],
  ["Rain Song", "Led Zeppelin"],
  ["Gimme Shelter", "The Rolling Stones"],
  ["Wild Horses", "The Rolling Stones"],
  ["Paint It, Black", "The Rolling Stones"],
  ["You Can't Always Get What You Want", "The Rolling Stones"],
  ["Beast of Burden", "The Rolling Stones"],
  ["Waiting on a Friend", "The Rolling Stones"],
  ["Riders on the Storm", "The Doors"],
  ["Light My Fire", "The Doors"],
  ["The End", "The Doors"],
  ["Break On Through", "The Doors"],
  ["Good Vibrations", "The Beach Boys"],
  ["God Only Knows", "The Beach Boys"],
  ["Wouldn't It Be Nice", "The Beach Boys"],
  ["In My Room", "The Beach Boys"],
  ["Don't Worry Baby", "The Beach Boys"],
  ["Sloop John B", "The Beach Boys"],
  ["Surf's Up", "The Beach Boys"],
  ["All Along the Watchtower", "Jimi Hendrix"],
  ["Little Wing", "Jimi Hendrix"],
  ["The Wind Cries Mary", "Jimi Hendrix"],
  ["Castles Made of Sand", "Jimi Hendrix"],
  ["Angel", "Jimi Hendrix"],
  ["Like a Rolling Stone", "Bob Dylan"],
  ["Blowin' in the Wind", "Bob Dylan"],
  ["The Times They Are A-Changin'", "Bob Dylan"],
  ["Don't Think Twice, It's All Right", "Bob Dylan"],
  ["Shelter from the Storm", "Bob Dylan"],
  ["Tangled Up in Blue", "Bob Dylan"],
  ["Knockin' on Heaven's Door", "Bob Dylan"],
  ["Forever Young", "Bob Dylan"],
  ["Make You Feel My Love", "Bob Dylan"],
  ["Into the Mystic", "Van Morrison"],
  ["Moondance", "Van Morrison"],
  ["Brown Eyed Girl", "Van Morrison"],
  ["Sweet Thing", "Van Morrison"],
  ["Crazy Love", "Van Morrison"],
  ["And It Stoned Me", "Van Morrison"],
  ["Tupelo Honey", "Van Morrison"],
  ["Days Like This", "Van Morrison"],
  ["Have You Ever Seen the Rain?", "Creedence Clearwater Revival"],
  ["Who'll Stop the Rain", "Creedence Clearwater Revival"],
  ["Bad Moon Rising", "Creedence Clearwater Revival"],
  ["Long As I Can See the Light", "Creedence Clearwater Revival"],
  ["Space Oddity", "David Bowie"],
  ["Life on Mars?", "David Bowie"],
  ["Heroes", "David Bowie"],
  ["Changes", "David Bowie"],
  ["Starman", "David Bowie"],
  ["Moonage Daydream", "David Bowie"],
  ["Dust in the Wind", "Kansas"],
  ["Carry On Wayward Son", "Kansas"],
  ["Free Bird", "Lynyrd Skynyrd"],
  ["Simple Man", "Lynyrd Skynyrd"],
  ["Tuesday's Gone", "Lynyrd Skynyrd"],
  ["Dream On", "Aerosmith"],
  ["Don't Stop Believin'", "Journey"],
  ["Faithfully", "Journey"],
  ["Lights", "Journey"],
  ["More Than a Feeling", "Boston"],
  ["Peace of Mind", "Boston"],
  ["Baba O'Riley", "The Who"],
  ["Behind Blue Eyes", "The Who"],
  ["Love Reign O'er Me", "The Who"],
  ["Time of the Season", "The Zombies"],
  ["This Will Be Our Year", "The Zombies"],
  ["A Whiter Shade of Pale", "Procol Harum"],
  ["Nights in White Satin", "The Moody Blues"],
  ["California Dreamin'", "The Mamas & The Papas"],
  ["Dream a Little Dream of Me", "The Mamas & The Papas"],
  ["Happy Together", "The Turtles"],
  ["Daydream Believer", "The Monkees"],
  ["I'm a Believer", "The Monkees"],
  ["Build Me Up Buttercup", "The Foundations"],
  ["Brown Sugar", "The Rolling Stones"],
  ["Crimson and Clover", "Tommy James & The Shondells"],
  ["House of the Rising Sun", "The Animals"],
  ["Don't Let Me Be Misunderstood", "The Animals"],
  ["For What It's Worth", "Buffalo Springfield"],
  ["White Rabbit", "Jefferson Airplane"],
  ["Somebody to Love", "Jefferson Airplane"],
  ["Piece of My Heart", "Big Brother & The Holding Company"],
  ["Me and Bobby McGee", "Janis Joplin"],
  ["Space Cowboy", "Steve Miller Band"],
  ["The Joker", "Steve Miller Band"],
  ["Fly Like an Eagle", "Steve Miller Band"],

  // ---- Motown / soul / funk ----
  ["What's Going On", "Marvin Gaye"],
  ["Let's Stay Together", "Al Green"],
  ["Tired of Being Alone", "Al Green"],
  ["Take Me to the River", "Al Green"],
  ["Ain't No Sunshine", "Bill Withers"],
  ["Lean on Me", "Bill Withers"],
  ["Lovely Day", "Bill Withers"],
  ["Grandma's Hands", "Bill Withers"],
  ["Just the Two of Us", "Bill Withers"],
  ["Use Me", "Bill Withers"],
  ["Sittin' on the Dock of the Bay", "Otis Redding"],
  ["These Arms of Mine", "Otis Redding"],
  ["Try a Little Tenderness", "Otis Redding"],
  ["That's How Strong My Love Is", "Otis Redding"],
  ["Stand by Me", "Ben E. King"],
  ["My Girl", "The Temptations"],
  ["Just My Imagination", "The Temptations"],
  ["Papa Was a Rollin' Stone", "The Temptations"],
  ["Ain't No Mountain High Enough", "Marvin Gaye & Tammi Terrell"],
  ["You're All I Need to Get By", "Marvin Gaye & Tammi Terrell"],
  ["Signed, Sealed, Delivered", "Stevie Wonder"],
  ["Isn't She Lovely", "Stevie Wonder"],
  ["As", "Stevie Wonder"],
  ["Sir Duke", "Stevie Wonder"],
  ["Superstition", "Stevie Wonder"],
  ["Higher Ground", "Stevie Wonder"],
  ["I Wish", "Stevie Wonder"],
  ["Golden Lady", "Stevie Wonder"],
  ["I Want You Back", "The Jackson 5"],
  ["ABC", "The Jackson 5"],
  ["I'll Be There", "The Jackson 5"],
  ["Respect", "Aretha Franklin"],
  ["I Say a Little Prayer", "Aretha Franklin"],
  ["A Natural Woman", "Aretha Franklin"],
  ["Chain of Fools", "Aretha Franklin"],
  ["At Last", "Etta James"],
  ["A Sunday Kind of Love", "Etta James"],
  ["I'd Rather Go Blind", "Etta James"],
  ["A Change Is Gonna Come", "Sam Cooke"],
  ["Bring It On Home to Me", "Sam Cooke"],
  ["Cupid", "Sam Cooke"],
  ["Wonderful World", "Sam Cooke"],
  ["Twistin' the Night Away", "Sam Cooke"],
  ["You Send Me", "Sam Cooke"],
  ["Green Onions", "Booker T. & the M.G.'s"],
  ["Move On Up", "Curtis Mayfield"],
  ["People Get Ready", "The Impressions"],
  ["Midnight Train to Georgia", "Gladys Knight & The Pips"],
  ["Ooo Baby Baby", "Smokey Robinson & The Miracles"],
  ["The Tracks of My Tears", "Smokey Robinson & The Miracles"],
  ["Cruisin'", "Smokey Robinson"],
  ["Let's Get It On", "Marvin Gaye"],
  ["Sexual Healing", "Marvin Gaye"],
  ["Mercy Mercy Me", "Marvin Gaye"],
  ["I Heard It Through the Grapevine", "Marvin Gaye"],
  ["September", "Earth, Wind & Fire"],
  ["Reasons", "Earth, Wind & Fire"],
  ["That's the Way of the World", "Earth, Wind & Fire"],
  ["Fantasy", "Earth, Wind & Fire"],
  ["Celebration", "Kool & The Gang"],
  ["Summer Madness", "Kool & The Gang"],
  ["Cherish", "Kool & The Gang"],
  ["Easy", "Commodores"],
  ["Zoom", "Commodores"],
  ["Sail On", "Commodores"],
  ["Three Times a Lady", "Commodores"],
  ["Best of My Love", "The Emotions"],
  ["Didn't I Blow Your Mind This Time", "The Delfonics"],
  ["La-La (Means I Love You)", "The Delfonics"],
  ["Betcha by Golly, Wow", "The Stylistics"],
  ["You Make Me Feel Brand New", "The Stylistics"],
  ["Love Train", "The O'Jays"],
  ["Back Stabbers", "The O'Jays"],
  ["Me and Mrs. Jones", "Billy Paul"],
  ["If You Don't Know Me by Now", "Harold Melvin & The Blue Notes"],
  ["Could It Be I'm Falling in Love", "The Spinners"],
  ["I'll Be Around", "The Spinners"],
  ["Everybody Plays the Fool", "The Main Ingredient"],

  // ---- 70s singer-songwriter / folk ----
  ["Fire and Rain", "James Taylor"],
  ["You've Got a Friend", "James Taylor"],
  ["Carolina in My Mind", "James Taylor"],
  ["Sweet Baby James", "James Taylor"],
  ["So Far Away", "Carole King"],
  ["It's Too Late", "Carole King"],
  ["I Feel the Earth Move", "Carole King"],
  ["Tapestry", "Carole King"],
  ["Will You Love Me Tomorrow", "Carole King"],
  ["Big Yellow Taxi", "Joni Mitchell"],
  ["Both Sides Now", "Joni Mitchell"],
  ["A Case of You", "Joni Mitchell"],
  ["River", "Joni Mitchell"],
  ["California", "Joni Mitchell"],
  ["The Circle Game", "Joni Mitchell"],
  ["Heart of Gold", "Neil Young"],
  ["Old Man", "Neil Young"],
  ["Harvest Moon", "Neil Young"],
  ["Comes a Time", "Neil Young"],
  ["Helpless", "Neil Young"],
  ["The Sound of Silence", "Simon & Garfunkel"],
  ["The Boxer", "Simon & Garfunkel"],
  ["Bridge Over Troubled Water", "Simon & Garfunkel"],
  ["Homeward Bound", "Simon & Garfunkel"],
  ["America", "Simon & Garfunkel"],
  ["Scarborough Fair", "Simon & Garfunkel"],
  ["Kathy's Song", "Simon & Garfunkel"],
  ["The Only Living Boy in New York", "Simon & Garfunkel"],
  ["April Come She Will", "Simon & Garfunkel"],
  ["A Hazy Shade of Winter", "Simon & Garfunkel"],
  ["Still Crazy After All These Years", "Paul Simon"],
  ["Graceland", "Paul Simon"],
  ["Slip Slidin' Away", "Paul Simon"],
  ["Father and Son", "Cat Stevens"],
  ["Wild World", "Cat Stevens"],
  ["Morning Has Broken", "Cat Stevens"],
  ["The Wind", "Cat Stevens"],
  ["Peace Train", "Cat Stevens"],
  ["Moonshadow", "Cat Stevens"],
  ["Oh Very Young", "Cat Stevens"],
  ["Take Me Home, Country Roads", "John Denver"],
  ["Leaving on a Jet Plane", "John Denver"],
  ["Annie's Song", "John Denver"],
  ["Rocky Mountain High", "John Denver"],
  ["Sunshine on My Shoulders", "John Denver"],
  ["American Pie", "Don McLean"],
  ["Vincent", "Don McLean"],
  ["Cat's in the Cradle", "Harry Chapin"],
  ["Time in a Bottle", "Jim Croce"],
  ["Operator", "Jim Croce"],
  ["I Got a Name", "Jim Croce"],
  ["If You Could Read My Mind", "Gordon Lightfoot"],
  ["Sundown", "Gordon Lightfoot"],
  ["Early Morning Rain", "Gordon Lightfoot"],
  ["Vienna", "Billy Joel"],
  ["Piano Man", "Billy Joel"],
  ["She's Always a Woman", "Billy Joel"],
  ["Just the Way You Are", "Billy Joel"],
  ["New York State of Mind", "Billy Joel"],
  ["Summer, Highland Falls", "Billy Joel"],
  ["And So It Goes", "Billy Joel"],
  ["Lucky Man", "Emerson, Lake & Palmer"],
  ["From the Beginning", "Emerson, Lake & Palmer"],
  ["Your Song", "Elton John"],
  ["Tiny Dancer", "Elton John"],
  ["Rocket Man", "Elton John"],
  ["Goodbye Yellow Brick Road", "Elton John"],
  ["Daniel", "Elton John"],
  ["Someone Saved My Life Tonight", "Elton John"],
  ["Mona Lisas and Mad Hatters", "Elton John"],
  ["Landslide", "Fleetwood Mac"],
  ["Dreams", "Fleetwood Mac"],
  ["Songbird", "Fleetwood Mac"],
  ["Never Going Back Again", "Fleetwood Mac"],
  ["Rhiannon", "Fleetwood Mac"],
  ["Sara", "Fleetwood Mac"],
  ["Gypsy", "Fleetwood Mac"],
  ["Everywhere", "Fleetwood Mac"],
  ["Little Lies", "Fleetwood Mac"],
  ["Go Your Own Way", "Fleetwood Mac"],
  ["The Chain", "Fleetwood Mac"],
  ["Hotel California", "Eagles"],
  ["Take It Easy", "Eagles"],
  ["Peaceful Easy Feeling", "Eagles"],
  ["Desperado", "Eagles"],
  ["New Kid in Town", "Eagles"],
  ["I Can't Tell You Why", "Eagles"],
  ["Already Gone", "Eagles"],
  ["Take It to the Limit", "Eagles"],
  ["Our House", "Crosby, Stills, Nash & Young"],
  ["Teach Your Children", "Crosby, Stills, Nash & Young"],
  ["Helplessly Hoping", "Crosby, Stills & Nash"],
  ["Suite: Judy Blue Eyes", "Crosby, Stills & Nash"],
  ["Southern Cross", "Crosby, Stills & Nash"],
  ["Sister Golden Hair", "America"],
  ["A Horse with No Name", "America"],
  ["Ventura Highway", "America"],
  ["Lonely People", "America"],
  ["Tin Man", "America"],
  ["Danny's Song", "Loggins & Messina"],
  ["House at Pooh Corner", "Loggins & Messina"],
  ["Doctor My Eyes", "Jackson Browne"],
  ["Running on Empty", "Jackson Browne"],
  ["These Days", "Jackson Browne"],
  ["Late for the Sky", "Jackson Browne"],
  ["The Weight", "The Band"],
  ["Up on Cripple Creek", "The Band"],
  ["It Makes No Difference", "The Band"],
  ["Ophelia", "The Band"],
  ["Wildflowers", "Tom Petty"],
  ["Free Fallin'", "Tom Petty"],
  ["Learning to Fly", "Tom Petty"],
  ["Wildflowers", "Dolly Parton"],
  ["The Night They Drove Old Dixie Down", "The Band"],
  ["If I Needed You", "Townes Van Zandt"],
  ["Pancho and Lefty", "Townes Van Zandt"],
  ["To Live Is to Fly", "Townes Van Zandt"],

  // ---- 80s ----
  ["Time After Time", "Cyndi Lauper"],
  ["True Colors", "Cyndi Lauper"],
  ["Girls Just Want to Have Fun", "Cyndi Lauper"],
  ["Take On Me", "a-ha"],
  ["Every Breath You Take", "The Police"],
  ["Message in a Bottle", "The Police"],
  ["Walking on the Moon", "The Police"],
  ["Fields of Gold", "Sting"],
  ["Shape of My Heart", "Sting"],
  ["Fragile", "Sting"],
  ["Brand New Day", "Sting"],
  ["In Your Eyes", "Peter Gabriel"],
  ["Solsbury Hill", "Peter Gabriel"],
  ["Don't Give Up", "Peter Gabriel"],
  ["Red Rain", "Peter Gabriel"],
  ["With or Without You", "U2"],
  ["Where the Streets Have No Name", "U2"],
  ["I Still Haven't Found What I'm Looking For", "U2"],
  ["One", "U2"],
  ["Beautiful Day", "U2"],
  ["Bad", "U2"],
  ["Under Pressure", "Queen & David Bowie"],
  ["Somebody to Love", "Queen"],
  ["Don't Stop Me Now", "Queen"],
  ["Love of My Life", "Queen"],
  ["The Show Must Go On", "Queen"],
  ["These Are the Days of Our Lives", "Queen"],
  ["Who Wants to Live Forever", "Queen"],
  ["Purple Rain", "Prince"],
  ["When Doves Cry", "Prince"],
  ["Raspberry Beret", "Prince"],
  ["Nothing Compares 2 U", "Sinéad O'Connor"],
  ["Sweet Child o' Mine", "Guns N' Roses"],
  ["Patience", "Guns N' Roses"],
  ["November Rain", "Guns N' Roses"],
  ["Livin' on a Prayer", "Bon Jovi"],
  ["Always", "Bon Jovi"],
  ["I'll Be There for You", "Bon Jovi"],
  ["Wanted Dead or Alive", "Bon Jovi"],
  ["Here I Go Again", "Whitesnake"],
  ["Eye of the Tiger", "Survivor"],
  ["The Search Is Over", "Survivor"],
  ["Africa", "TOTO"],
  ["Rosanna", "TOTO"],
  ["Hold the Line", "TOTO"],
  ["Everybody Wants to Rule the World", "Tears for Fears"],
  ["Head Over Heels", "Tears for Fears"],
  ["Mad World", "Tears for Fears"],
  ["Shout", "Tears for Fears"],
  ["Just Like Heaven", "The Cure"],
  ["Pictures of You", "The Cure"],
  ["Lovesong", "The Cure"],
  ["Friday I'm in Love", "The Cure"],
  ["Boys Don't Cry", "The Cure"],
  ["There Is a Light That Never Goes Out", "The Smiths"],
  ["Please, Please, Please, Let Me Get What I Want", "The Smiths"],
  ["This Charming Man", "The Smiths"],
  ["Asleep", "The Smiths"],
  ["Bizarre Love Triangle", "New Order"],
  ["Blue Monday", "New Order"],
  ["Love Will Tear Us Apart", "Joy Division"],
  ["Atmosphere", "Joy Division"],
  ["Once in a Lifetime", "Talking Heads"],
  ["This Must Be the Place (Naive Melody)", "Talking Heads"],
  ["Burning Down the House", "Talking Heads"],
  ["And She Was", "Talking Heads"],
  ["Road to Nowhere", "Talking Heads"],
  ["Dancing in the Dark", "Bruce Springsteen"],
  ["I'm on Fire", "Bruce Springsteen"],
  ["The River", "Bruce Springsteen"],
  ["Atlantic City", "Bruce Springsteen"],
  ["Thunder Road", "Bruce Springsteen"],
  ["Born to Run", "Bruce Springsteen"],
  ["Secret Garden", "Bruce Springsteen"],
  ["Streets of Philadelphia", "Bruce Springsteen"],
  ["Everybody Hurts", "R.E.M."],
  ["Losing My Religion", "R.E.M."],
  ["Nightswimming", "R.E.M."],
  ["Man on the Moon", "R.E.M."],
  ["The One I Love", "R.E.M."],
  ["Sweet Dreams (Are Made of This)", "Eurythmics"],
  ["Here Comes the Rain Again", "Eurythmics"],
  ["Tainted Love", "Soft Cell"],
  ["Don't You (Forget About Me)", "Simple Minds"],
  ["Alive and Kicking", "Simple Minds"],
  ["Space Age Love Song", "A Flock of Seagulls"],
  ["I Ran (So Far Away)", "A Flock of Seagulls"],
  ["I Melt with You", "Modern English"],
  ["Only You", "Yazoo"],
  ["True", "Spandau Ballet"],
  ["Hold Me Now", "Thompson Twins"],
  ["If You Leave", "Orchestral Manoeuvres in the Dark"],
  ["Drive", "The Cars"],
  ["Time Will Reveal", "DeBarge"],
  ["Rhythm of the Night", "DeBarge"],
  ["All This Love", "DeBarge"],
  ["Careless Whisper", "George Michael"],
  ["Faith", "George Michael"],
  ["Father Figure", "George Michael"],
  ["Billie Jean", "Michael Jackson"],
  ["Human Nature", "Michael Jackson"],
  ["Man in the Mirror", "Michael Jackson"],
  ["Rock with You", "Michael Jackson"],
  ["I Can't Help It", "Michael Jackson"],
  ["The Way You Make Me Feel", "Michael Jackson"],
  ["How Will I Know", "Whitney Houston"],
  ["I Wanna Dance with Somebody", "Whitney Houston"],
  ["Greatest Love of All", "Whitney Houston"],
  ["Higher Love", "Steve Winwood"],
  ["Valerie", "Steve Winwood"],
  ["The Boys of Summer", "Don Henley"],
  ["The End of the Innocence", "Don Henley"],

  // ---- 90s ----
  ["Wonderwall", "Oasis"],
  ["Don't Look Back in Anger", "Oasis"],
  ["Champagne Supernova", "Oasis"],
  ["Live Forever", "Oasis"],
  ["Stand by Me", "Oasis"],
  ["Slide Away", "Oasis"],
  ["Bitter Sweet Symphony", "The Verve"],
  ["Lucky Man", "The Verve"],
  ["The Drugs Don't Work", "The Verve"],
  ["Creep", "Radiohead"],
  ["Fake Plastic Trees", "Radiohead"],
  ["High and Dry", "Radiohead"],
  ["No Surprises", "Radiohead"],
  ["Karma Police", "Radiohead"],
  ["Let Down", "Radiohead"],
  ["Exit Music (For a Film)", "Radiohead"],
  ["How to Disappear Completely", "Radiohead"],
  ["Everything in Its Right Place", "Radiohead"],
  ["Black", "Pearl Jam"],
  ["Alive", "Pearl Jam"],
  ["Yellow Ledbetter", "Pearl Jam"],
  ["Just Breathe", "Pearl Jam"],
  ["Better Man", "Pearl Jam"],
  ["Elderly Woman Behind the Counter in a Small Town", "Pearl Jam"],
  ["Come as You Are", "Nirvana"],
  ["All Apologies", "Nirvana"],
  ["Something in the Way", "Nirvana"],
  ["About a Girl", "Nirvana"],
  ["Heart-Shaped Box", "Nirvana"],
  ["The Man Who Sold the World", "Nirvana"],
  ["Where Did You Sleep Last Night", "Nirvana"],
  ["Black Hole Sun", "Soundgarden"],
  ["Fell on Black Days", "Soundgarden"],
  ["Hunger Strike", "Temple of the Dog"],
  ["I Don't Want to Miss a Thing", "Aerosmith"],
  ["Under the Bridge", "Red Hot Chili Peppers"],
  ["Soul to Squeeze", "Red Hot Chili Peppers"],
  ["Scar Tissue", "Red Hot Chili Peppers"],
  ["Otherside", "Red Hot Chili Peppers"],
  ["Californication", "Red Hot Chili Peppers"],
  ["Road Trippin'", "Red Hot Chili Peppers"],
  ["1979", "The Smashing Pumpkins"],
  ["Tonight, Tonight", "The Smashing Pumpkins"],
  ["Disarm", "The Smashing Pumpkins"],
  ["Landslide", "The Smashing Pumpkins"],
  ["Mayonaise", "The Smashing Pumpkins"],
  ["Today", "The Smashing Pumpkins"],
  ["No Rain", "Blind Melon"],
  ["Glycerine", "Bush"],
  ["Iris", "The Goo Goo Dolls"],
  ["Name", "The Goo Goo Dolls"],
  ["Slide", "The Goo Goo Dolls"],
  ["Black Balloon", "The Goo Goo Dolls"],
  ["3 AM", "Matchbox Twenty"],
  ["Push", "Matchbox Twenty"],
  ["If You Could Only See", "Tonic"],
  ["Closing Time", "Semisonic"],
  ["The Freshmen", "The Verve Pipe"],
  ["Good", "Better Than Ezra"],
  ["Lightning Crashes", "Live"],
  ["I Alone", "Live"],
  ["Runaway Train", "Soul Asylum"],
  ["Two Princes", "Spin Doctors"],
  ["Mr. Jones", "Counting Crows"],
  ["Round Here", "Counting Crows"],
  ["A Long December", "Counting Crows"],
  ["Colorblind", "Counting Crows"],
  ["Only Wanna Be with You", "Hootie & The Blowfish"],
  ["Let Her Cry", "Hootie & The Blowfish"],
  ["Time", "Hootie & The Blowfish"],
  ["Everything Zen", "Bush"],
  ["Zombie", "The Cranberries"],
  ["Linger", "The Cranberries"],
  ["Dreams", "The Cranberries"],
  ["When You're Gone", "The Cranberries"],
  ["Ode to My Family", "The Cranberries"],
  ["Torn", "Natalie Imbruglia"],
  ["You Were Meant for Me", "Jewel"],
  ["Who Will Save Your Soul", "Jewel"],
  ["Foolish Games", "Jewel"],
  ["Hands", "Jewel"],
  ["Building a Mystery", "Sarah McLachlan"],
  ["Angel", "Sarah McLachlan"],
  ["I Will Remember You", "Sarah McLachlan"],
  ["Adia", "Sarah McLachlan"],
  ["Kiss Me", "Sixpence None the Richer"],
  ["There She Goes", "Sixpence None the Richer"],
  ["Save Tonight", "Eagle-Eye Cherry"],
  ["Lovefool", "The Cardigans"],
  ["Fade Into You", "Mazzy Star"],
  ["Into Dust", "Mazzy Star"],
  ["Wild Horses", "The Sundays"],
  ["Here's Where the Story Ends", "The Sundays"],
  ["No Diggity", "Blackstreet"],
  ["Waterfalls", "TLC"],
  ["Creep", "TLC"],
  ["Killing Me Softly with His Song", "Fugees"],
  ["Ready or Not", "Fugees"],
  ["Doo Wop (That Thing)", "Lauryn Hill"],
  ["Ex-Factor", "Lauryn Hill"],
  ["Everything Is Everything", "Lauryn Hill"],
  ["The Rain (Supa Dupa Fly)", "Missy Elliott"],
  ["Are You That Somebody", "Aaliyah"],
  ["One in a Million", "Aaliyah"],
  ["Pony", "Ginuwine"],
  ["This Is How We Do It", "Montell Jordan"],
  ["Return of the Mack", "Mark Morrison"],

  // ---- 2000s ----
  ["Yellow", "Coldplay"],
  ["Fix You", "Coldplay"],
  ["The Scientist", "Coldplay"],
  ["Clocks", "Coldplay"],
  ["In My Place", "Coldplay"],
  ["Green Eyes", "Coldplay"],
  ["Warning Sign", "Coldplay"],
  ["Sparks", "Coldplay"],
  ["Don't Panic", "Coldplay"],
  ["Viva la Vida", "Coldplay"],
  ["Speed of Sound", "Coldplay"],
  ["Swallowed in the Sea", "Coldplay"],
  ["Till Kingdom Come", "Coldplay"],
  ["Mr. Brightside", "The Killers"],
  ["When You Were Young", "The Killers"],
  ["All These Things That I've Done", "The Killers"],
  ["Read My Mind", "The Killers"],
  ["Human", "The Killers"],
  ["Last Nite", "The Strokes"],
  ["Someday", "The Strokes"],
  ["Reptilia", "The Strokes"],
  ["Under Control", "The Strokes"],
  ["You Only Live Once", "The Strokes"],
  ["I'll Try Anything Once", "The Strokes"],
  ["Seven Nation Army", "The White Stripes"],
  ["We're Going to Be Friends", "The White Stripes"],
  ["Fell in Love with a Girl", "The White Stripes"],
  ["Float On", "Modest Mouse"],
  ["The World at Large", "Modest Mouse"],
  ["Gravity Rides Everything", "Modest Mouse"],
  ["Such Great Heights", "The Postal Service"],
  ["The District Sleeps Alone Tonight", "The Postal Service"],
  ["Brand New Colony", "The Postal Service"],
  ["Soul Meets Body", "Death Cab for Cutie"],
  ["I Will Follow You into the Dark", "Death Cab for Cutie"],
  ["Transatlanticism", "Death Cab for Cutie"],
  ["A Lack of Color", "Death Cab for Cutie"],
  ["Title and Registration", "Death Cab for Cutie"],
  ["Passenger Seat", "Death Cab for Cutie"],
  ["The New Year", "Death Cab for Cutie"],
  ["Marching Bands of Manhattan", "Death Cab for Cutie"],
  ["Chicago", "Sufjan Stevens"],
  ["To Be Alone with You", "Sufjan Stevens"],
  ["Casimir Pulaski Day", "Sufjan Stevens"],
  ["The Only Thing", "Sufjan Stevens"],
  ["Should Have Known Better", "Sufjan Stevens"],
  ["Fourth of July", "Sufjan Stevens"],
  ["Death with Dignity", "Sufjan Stevens"],
  ["Mystery of Love", "Sufjan Stevens"],
  ["Visions of Gideon", "Sufjan Stevens"],
  ["First Day of My Life", "Bright Eyes"],
  ["Lua", "Bright Eyes"],
  ["Bowl of Oranges", "Bright Eyes"],
  ["At the Bottom of Everything", "Bright Eyes"],
  ["Poison Oak", "Bright Eyes"],
  ["Lover I Don't Have to Love", "Bright Eyes"],
  ["Skinny Love", "Bon Iver"],
  ["Holocene", "Bon Iver"],
  ["Re: Stacks", "Bon Iver"],
  ["For Emma", "Bon Iver"],
  ["Flume", "Bon Iver"],
  ["Blood Bank", "Bon Iver"],
  ["Calgary", "Bon Iver"],
  ["Towers", "Bon Iver"],
  ["Beth/Rest", "Bon Iver"],
  ["8 (circle)", "Bon Iver"],
  ["29 #Strafford APTS", "Bon Iver"],
  ["Hey Ya!", "OutKast"],
  ["Ms. Jackson", "OutKast"],
  ["So Fresh, So Clean", "OutKast"],
  ["The Way You Move", "OutKast"],
  ["Roses", "OutKast"],
  ["Crazy", "Gnarls Barkley"],
  ["Gold Digger", "Kanye West"],
  ["Heartless", "Kanye West"],
  ["Flashing Lights", "Kanye West"],
  ["Street Lights", "Kanye West"],
  ["Runaway", "Kanye West"],
  ["Devil in a New Dress", "Kanye West"],
  ["Bound 2", "Kanye West"],
  ["Ultralight Beam", "Kanye West"],
  ["Ghost Town", "Kanye West"],
  ["Violet Hill", "Coldplay"],
  ["Boston", "Augustana"],
  ["How to Save a Life", "The Fray"],
  ["Over My Head (Cable Car)", "The Fray"],
  ["You Found Me", "The Fray"],
  ["Chasing Cars", "Snow Patrol"],
  ["Run", "Snow Patrol"],
  ["Open Your Eyes", "Snow Patrol"],
  ["Set the Fire to the Third Bar", "Snow Patrol"],
  ["The Blower's Daughter", "Damien Rice"],
  ["Cannonball", "Damien Rice"],
  ["9 Crimes", "Damien Rice"],
  ["Delicate", "Damien Rice"],
  ["Volcano", "Damien Rice"],
  ["Breathe Me", "Sia"],
  ["Chasing Pavements", "Adele"],
  ["Make You Feel My Love", "Adele"],
  ["Hometown Glory", "Adele"],
  ["Someone Like You", "Adele"],
  ["Set Fire to the Rain", "Adele"],
  ["Turning Tables", "Adele"],
  ["When We Were Young", "Adele"],
  ["All I Ask", "Adele"],
  ["The One", "Kodaline"],
  ["All I Want", "Kodaline"],
  ["High Hopes", "Kodaline"],
  ["Banana Pancakes", "Jack Johnson"],
  ["Better Together", "Jack Johnson"],
  ["Sitting, Waiting, Wishing", "Jack Johnson"],
  ["Upside Down", "Jack Johnson"],
  ["Breakdown", "Jack Johnson"],
  ["Flake", "Jack Johnson"],
  ["Do You Remember", "Jack Johnson"],
  ["Angel", "Jack Johnson"],
  ["Only the Ocean", "Jack Johnson"],
  ["Gone", "Jack Johnson"],
  ["Wasting Time", "Jack Johnson"],
  ["Times Like These", "Jack Johnson"],
  ["I'm Yours", "Jason Mraz"],
  ["Lucky", "Jason Mraz"],
  ["93 Million Miles", "Jason Mraz"],
  ["Ordinary People", "John Legend"],
  ["All of Me", "John Legend"],
  ["Stay with You", "John Legend"],
  ["So High", "John Legend"],
  ["Gravity", "John Mayer"],
  ["Slow Dancing in a Burning Room", "John Mayer"],
  ["Stop This Train", "John Mayer"],
  ["Dreaming with a Broken Heart", "John Mayer"],
  ["The Age of Worry", "John Mayer"],
  ["Wildfire", "John Mayer"],
  ["In the Blood", "John Mayer"],
  ["Edge of Desire", "John Mayer"],
  ["Heart of Life", "John Mayer"],
  ["Daughters", "John Mayer"],
  ["Why Georgia", "John Mayer"],
  ["3x5", "John Mayer"],
  ["Clarity", "John Mayer"],
  ["Free Fallin' (Live)", "John Mayer"],
  ["New Light", "John Mayer"],
  ["Moving On and Getting Over", "John Mayer"],
  ["Changing", "John Mayer"],
  ["You're Beautiful", "James Blunt"],
  ["Goodbye My Lover", "James Blunt"],
  ["Collide", "Howie Day"],
  ["Bad Day", "Daniel Powter"],
  ["Put Your Records On", "Corinne Bailey Rae"],
  ["Like a Star", "Corinne Bailey Rae"],
  ["Bubbly", "Colbie Caillat"],
  ["Realize", "Colbie Caillat"],
  ["Hallelujah", "Jeff Buckley"],
  ["Lover, You Should've Come Over", "Jeff Buckley"],
  ["Grace", "Jeff Buckley"],
  ["Last Goodbye", "Jeff Buckley"],
  ["The Luckiest", "Ben Folds"],
  ["Still Fighting It", "Ben Folds"],
  ["The Great Escape", "Patrick Watson"],
  ["Lighthouse", "Patrick Watson"],

  // ---- 2010s indie / folk / alt ----
  ["Rivers and Roads", "The Head and the Heart"],
  ["Lost in My Mind", "The Head and the Heart"],
  ["Down in the Valley", "The Head and the Heart"],
  ["Winter Song", "The Head and the Heart"],
  ["Let's Be Still", "The Head and the Heart"],
  ["Another Story", "The Head and the Heart"],
  ["Ho Hey", "The Lumineers"],
  ["Stubborn Love", "The Lumineers"],
  ["Ophelia", "The Lumineers"],
  ["Cleopatra", "The Lumineers"],
  ["Sleep on the Floor", "The Lumineers"],
  ["Angela", "The Lumineers"],
  ["Gale Song", "The Lumineers"],
  ["Slow It Down", "The Lumineers"],
  ["Flowers in Your Hair", "The Lumineers"],
  ["Gloria", "The Lumineers"],
  ["Salt and the Sea", "The Lumineers"],
  ["Where the Skies Are Blue", "The Lumineers"],
  ["I Will Wait", "Mumford & Sons"],
  ["The Cave", "Mumford & Sons"],
  ["Little Lion Man", "Mumford & Sons"],
  ["After the Storm", "Mumford & Sons"],
  ["Awake My Soul", "Mumford & Sons"],
  ["Ghosts That We Knew", "Mumford & Sons"],
  ["Hopeless Wanderer", "Mumford & Sons"],
  ["Below My Feet", "Mumford & Sons"],
  ["Home", "Edward Sharpe & The Magnetic Zeros"],
  ["Man on Fire", "Edward Sharpe & The Magnetic Zeros"],
  ["40 Day Dream", "Edward Sharpe & The Magnetic Zeros"],
  ["Dog Days Are Over", "Florence + The Machine"],
  ["Shake It Out", "Florence + The Machine"],
  ["Cosmic Love", "Florence + The Machine"],
  ["Never Let Me Go", "Florence + The Machine"],
  ["The Night We Met", "Lord Huron"],
  ["Ends of the Earth", "Lord Huron"],
  ["Meet Me in the Woods", "Lord Huron"],
  ["Wait by the River", "Lord Huron"],
  ["Long Lost", "Lord Huron"],
  ["Mine Forever", "Lord Huron"],
  ["Love Like Ghosts", "Lord Huron"],
  ["She Lit a Fire", "Lord Huron"],
  ["Bloom", "The Paper Kites"],
  ["Featherstone", "The Paper Kites"],
  ["Willow Tree March", "The Paper Kites"],
  ["On the Train Ride Home", "The Paper Kites"],
  ["Too Late", "The Paper Kites"],
  ["Arrow", "The Paper Kites"],
  ["Take Me Home", "Aron Wright"],
  ["Look After You", "Aron Wright"],
  ["Big Black Car", "Gregory Alan Isakov"],
  ["The Stable Song", "Gregory Alan Isakov"],
  ["Amsterdam", "Gregory Alan Isakov"],
  ["San Luis", "Gregory Alan Isakov"],
  ["If I Go, I'm Goin", "Gregory Alan Isakov"],
  ["Dark, Dark, Dark", "Gregory Alan Isakov"],
  ["Southern Star", "Gregory Alan Isakov"],
  ["Second Chances", "Gregory Alan Isakov"],
  ["Saint Valentine", "Gregory Alan Isakov"],
  ["Time Will Tell", "Gregory Alan Isakov"],
  ["Master & a Hound", "Gregory Alan Isakov"],
  ["3 a.m.", "Gregory Alan Isakov"],
  ["Idaho", "Gregory Alan Isakov"],
  ["She Always Takes It Black", "Gregory Alan Isakov"],
  ["Liars", "Gregory Alan Isakov"],
  ["Was I Just Another One", "Gregory Alan Isakov"],
  ["Words", "Gregory Alan Isakov"],
  ["Honey, It's Alright", "Gregory Alan Isakov"],
  ["Living Proof", "Gregory Alan Isakov"],
  ["Watchman", "Gregory Alan Isakov"],
  ["Berth", "Gregory Alan Isakov"],
  ["Appaloosa Bones", "Gregory Alan Isakov"],
  ["Silver Bell", "Gregory Alan Isakov"],
  ["One Day", "Gregory Alan Isakov"],
  ["Sweet Heat Lightning", "Gregory Alan Isakov"],
  ["Miles to Go", "Gregory Alan Isakov"],
  ["Terlingua", "Gregory Alan Isakov"],
  ["The Fall", "Gregory Alan Isakov"],
  ["Wings in All Black", "Gregory Alan Isakov"],
  ["Feet Don't Fail Me Now", "Joy Oladokun"],
  ["Keep on Keeping On", "Colony House"],
  ["Silhouettes", "Colony House"],
  ["You & I", "Colony House"],
  ["Moving Forward", "Colony House"],
  ["Cannonballers", "Colony House"],
  ["Landmine", "Sum 41"],
  ["Holocene (Live)", "Bon Iver"],
  ["Heartbeats", "José González"],
  ["Crosses", "José González"],
  ["Stay Alive", "José González"],
  ["Step Out", "José González"],
  ["Open Book", "José González"],
  ["Leaf Off / The Cave", "José González"],
  ["Cycling Trivialities", "José González"],
  ["Down the Line", "José González"],
  ["Hideaway", "José González"],
  ["The Forest", "José González"],
  ["With the Ink of a Ghost", "José González"],
  ["Every Age", "José González"],
  ["Line of Fire", "Junip"],
  ["Your Life Your Call", "Junip"],
  ["Holdin On", "Flume"],
  ["Never Be Like You", "Flume"],
  ["Says", "Nils Frahm"],
  ["Sunson", "Nils Frahm"],
  ["Intro", "The xx"],
  ["Angels", "The xx"],
  ["On Hold", "The xx"],
  ["Sweet Disposition", "The Temper Trap"],
  ["Little Talks", "Of Monsters and Men"],
  ["Dirty Paws", "Of Monsters and Men"],
  ["Mountain Sound", "Of Monsters and Men"],
  ["King and Lionheart", "Of Monsters and Men"],
  ["Yellow Light", "Of Monsters and Men"],
  ["Lakehouse", "Of Monsters and Men"],
  ["Riptide", "Vance Joy"],
  ["Mess Is Mine", "Vance Joy"],
  ["Fire and the Flood", "Vance Joy"],
  ["Georgia", "Vance Joy"],
  ["Lay It on Me", "Vance Joy"],
  ["Call If You Need Me", "Vance Joy"],
  ["We're Going Home", "Vance Joy"],
  ["Saturday Sun", "Vance Joy"],
  ["Missing Piece", "Vance Joy"],
  ["Budapest", "George Ezra"],
  ["Blame It on Me", "George Ezra"],
  ["Barcelona", "George Ezra"],
  ["Shotgun", "George Ezra"],
  ["Hold My Girl", "George Ezra"],
  ["Paradise", "George Ezra"],
  ["Let Her Go", "Passenger"],
  ["Life's for the Living", "Passenger"],
  ["The Wrong Direction", "Passenger"],
  ["Whispers", "Passenger"],
  ["Scare Away the Dark", "Passenger"],
  ["Heart's on Fire", "Passenger"],
  ["Home", "Phillip Phillips"],
  ["Gone, Gone, Gone", "Phillip Phillips"],
  ["Raging Fire", "Phillip Phillips"],
  ["I Lived", "OneRepublic"],
  ["Counting Stars", "OneRepublic"],
  ["Good Life", "OneRepublic"],
  ["Secrets", "OneRepublic"],
  ["Apologize", "OneRepublic"],
  ["Stop and Stare", "OneRepublic"],
  ["Come Home", "OneRepublic"],
  ["Better Days", "OneRepublic"],
  ["Wherever I Go", "OneRepublic"],
  ["Something I Need", "OneRepublic"],
  ["Pompeii", "Bastille"],
  ["Flaws", "Bastille"],
  ["Oblivion", "Bastille"],
  ["Good Grief", "Bastille"],
  ["Happier", "Bastille"],
  ["Safe and Sound", "Capital Cities"],
  ["On Top of the World", "Imagine Dragons"],
  ["Demons", "Imagine Dragons"],
  ["It's Time", "Imagine Dragons"],
  ["Bleeding Out", "Imagine Dragons"],
  ["Next to Me", "Imagine Dragons"],
  ["Walking the Wire", "Imagine Dragons"],
  ["Stubborn Love (Live)", "The Lumineers"],
  ["Take Me to Church", "Hozier"],
  ["Work Song", "Hozier"],
  ["Cherry Wine", "Hozier"],
  ["From Eden", "Hozier"],
  ["In a Week", "Hozier"],
  ["Shrike", "Hozier"],
  ["Almost (Sweet Music)", "Hozier"],
  ["Movement", "Hozier"],
  ["Wasteland, Baby!", "Hozier"],
  ["Would That I", "Hozier"],
  ["First Time", "Hozier"],
  ["Francesca", "Hozier"],
  ["Unknown / Nth", "Hozier"],
  ["Too Sweet", "Hozier"],
  ["Budapest (Live)", "George Ezra"],
  ["Stressed Out", "Twenty One Pilots"],
  ["Ride", "Twenty One Pilots"],
  ["Car Radio", "Twenty One Pilots"],
  ["Tear in My Heart", "Twenty One Pilots"],
  ["Trees", "Twenty One Pilots"],
  ["Youngblood", "5 Seconds of Summer"],
  ["Sweater Weather", "The Neighbourhood"],
  ["Daddy Issues", "The Neighbourhood"],
  ["Softcore", "The Neighbourhood"],
  ["Reflections", "The Neighbourhood"],
  ["The Beach", "The Neighbourhood"],
  ["You Get Me So High", "The Neighbourhood"],
  ["Somebody Else", "The 1975"],
  ["Robbers", "The 1975"],
  ["Chocolate", "The 1975"],
  ["Love It If We Made It", "The 1975"],
  ["It's Not Living (If It's Not with You)", "The 1975"],
  ["Paris", "The 1975"],
  ["fallingforyou", "The 1975"],
  ["About You", "The 1975"],
  ["Electric Feel", "MGMT"],
  ["Kids", "MGMT"],
  ["Time to Pretend", "MGMT"],
  ["Little Dark Age", "MGMT"],
  ["Midnight City", "M83"],
  ["Wait", "M83"],
  ["Outro", "M83"],
  ["Do It, Try It", "M83"],
  ["Tokyo Narita", "HONNE"],
  ["Day 1", "HONNE"],
  ["Warm on a Cold Night", "HONNE"],
  ["Someone That Loves You", "HONNE"],
  ["Location Unknown", "HONNE"],
  ["Crying Over You", "HONNE"],
  ["Dead of Night", "Orville Peck"],
  ["Ocean Eyes", "Billie Eilish"],
  ["idontwannabeyouanymore", "Billie Eilish"],
  ["when the party's over", "Billie Eilish"],
  ["everything i wanted", "Billie Eilish"],
  ["i love you", "Billie Eilish"],
  ["Happier Than Ever", "Billie Eilish"],
  ["What Was I Made For?", "Billie Eilish"],
  ["Birds of a Feather", "Billie Eilish"],
  ["Wildflower", "Billie Eilish"],
  ["Blue", "Billie Eilish"],

  // ---- 2010s pop / R&B ----
  ["Thinking Out Loud", "Ed Sheeran"],
  ["Photograph", "Ed Sheeran"],
  ["Perfect", "Ed Sheeran"],
  ["Castle on the Hill", "Ed Sheeran"],
  ["The A Team", "Ed Sheeran"],
  ["Lego House", "Ed Sheeran"],
  ["Tenerife Sea", "Ed Sheeran"],
  ["All of the Stars", "Ed Sheeran"],
  ["Afterglow", "Ed Sheeran"],
  ["Stay", "Rihanna"],
  ["Diamonds", "Rihanna"],
  ["We Found Love", "Rihanna"],
  ["Love on the Brain", "Rihanna"],
  ["Needed Me", "Rihanna"],
  ["Halo", "Beyoncé"],
  ["XO", "Beyoncé"],
  ["Love On Top", "Beyoncé"],
  ["1+1", "Beyoncé"],
  ["All Night", "Beyoncé"],
  ["Sandcastles", "Beyoncé"],
  ["Cranes in the Sky", "Solange"],
  ["Adorn", "Miguel"],
  ["Sure Thing", "Miguel"],
  ["Coffee", "Miguel"],
  ["Sky Walker", "Miguel"],
  ["Thinkin Bout You", "Frank Ocean"],
  ["Pink + White", "Frank Ocean"],
  ["Self Control", "Frank Ocean"],
  ["Nights", "Frank Ocean"],
  ["Godspeed", "Frank Ocean"],
  ["White Ferrari", "Frank Ocean"],
  ["Ivy", "Frank Ocean"],
  ["Moon River", "Frank Ocean"],
  ["Sweet Life", "Frank Ocean"],
  ["Lost", "Frank Ocean"],
  ["Pyramids", "Frank Ocean"],
  ["Chanel", "Frank Ocean"],
  ["Solo", "Frank Ocean"],
  ["Seigfried", "Frank Ocean"],
  ["Bad Religion", "Frank Ocean"],
  ["Forrest Gump", "Frank Ocean"],
  ["Super Rich Kids", "Frank Ocean"],
  ["The Less I Know the Better", "Tame Impala"],
  ["Let It Happen", "Tame Impala"],
  ["Eventually", "Tame Impala"],
  ["Yes I'm Changing", "Tame Impala"],
  ["New Person, Same Old Mistakes", "Tame Impala"],
  ["Borderline", "Tame Impala"],
  ["Lost in Yesterday", "Tame Impala"],
  ["On Track", "Tame Impala"],
  ["Feels Like We Only Go Backwards", "Tame Impala"],
  ["Redbone", "Childish Gambino"],
  ["3005", "Childish Gambino"],
  ["Sober", "Childish Gambino"],
  ["Me and Your Mama", "Childish Gambino"],
  ["Stand Tall", "Childish Gambino"],
  ["Get You", "Daniel Caesar"],
  ["Best Part", "Daniel Caesar"],
  ["Blessed", "Daniel Caesar"],
  ["Japanese Denim", "Daniel Caesar"],
  ["Always", "Daniel Caesar"],
  ["Come Through and Chill", "Miguel"],
  ["Location", "Khalid"],
  ["Young Dumb & Broke", "Khalid"],
  ["Better", "Khalid"],
  ["Talk", "Khalid"],
  ["Saved", "Khalid"],
  ["Suncity", "Khalid"],
  ["Lovely", "Billie Eilish & Khalid"],
  ["Electric", "Alina Baraz"],
  ["Fantasy", "Alina Baraz"],
  ["Fool for You", "Snoh Aalegra"],
  ["I Want You Around", "Snoh Aalegra"],
  ["Come Home", "Anderson .Paak"],
  ["Make It Better", "Anderson .Paak"],
  ["Tints", "Anderson .Paak"],
  ["The Bird", "Anderson .Paak"],
  ["Put Me Thru", "Anderson .Paak"],
  ["Am I Wrong", "Anderson .Paak"],
  ["Suede", "NxWorries"],
  ["Lyk Dis", "NxWorries"],
  ["Pretty Little Fears", "6LACK"],
  ["Prblms", "6LACK"],
  ["Exchange", "Bryson Tiller"],
  ["Don't", "Bryson Tiller"],
  ["The Hills", "The Weeknd"],
  ["Call Out My Name", "The Weeknd"],
  ["Earned It", "The Weeknd"],
  ["Die For You", "The Weeknd"],
  ["Out of Time", "The Weeknd"],
  ["Blinding Lights", "The Weeknd"],
  ["After Hours", "The Weeknd"],
  ["Is There Someone Else?", "The Weeknd"],

  // ---- hip-hop ----
  ["Juicy", "The Notorious B.I.G."],
  ["Big Poppa", "The Notorious B.I.G."],
  ["Dear Mama", "2Pac"],
  ["California Love", "2Pac"],
  ["Changes", "2Pac"],
  ["Keep Ya Head Up", "2Pac"],
  ["Life Goes On", "2Pac"],
  ["N.Y. State of Mind", "Nas"],
  ["The World Is Yours", "Nas"],
  ["One Mic", "Nas"],
  ["If I Ruled the World", "Nas"],
  ["C.R.E.A.M.", "Wu-Tang Clan"],
  ["Can It Be All So Simple", "Wu-Tang Clan"],
  ["93 'til Infinity", "Souls of Mischief"],
  ["The Light", "Common"],
  ["I Used to Love H.E.R.", "Common"],
  ["The Corner", "Common"],
  ["Be", "Common"],
  ["They Say", "Common"],
  ["Electric Relaxation", "A Tribe Called Quest"],
  ["Can I Kick It?", "A Tribe Called Quest"],
  ["Find a Way", "A Tribe Called Quest"],
  ["Bonita Applebum", "A Tribe Called Quest"],
  ["Award Tour", "A Tribe Called Quest"],
  ["Passin' Me By", "The Pharcyde"],
  ["Runnin'", "The Pharcyde"],
  ["The Next Movement", "The Roots"],
  ["You Got Me", "The Roots"],
  ["Act Too (The Love of My Life)", "The Roots"],
  ["The Seed (2.0)", "The Roots"],
  ["Ms. Fat Booty", "Mos Def"],
  ["Umi Says", "Mos Def"],
  ["Mathematics", "Mos Def"],
  ["Respiration", "Black Star"],
  ["Definition", "Black Star"],
  ["Get By", "Talib Kweli"],
  ["The Blast", "Talib Kweli"],
  ["Daughters", "Nas"],
  ["Sing About Me, I'm Dying of Thirst", "Kendrick Lamar"],
  ["Money Trees", "Kendrick Lamar"],
  ["Bitch, Don't Kill My Vibe", "Kendrick Lamar"],
  ["Alright", "Kendrick Lamar"],
  ["How Much a Dollar Cost", "Kendrick Lamar"],
  ["LOVE.", "Kendrick Lamar"],
  ["PRIDE.", "Kendrick Lamar"],
  ["FEAR.", "Kendrick Lamar"],
  ["DUCKWORTH.", "Kendrick Lamar"],
  ["Poetic Justice", "Kendrick Lamar"],
  ["The Recipe", "Kendrick Lamar"],
  ["Die Hard", "Kendrick Lamar"],
  ["Count Me Out", "Kendrick Lamar"],
  ["Mother I Sober", "Kendrick Lamar"],
  ["No Role Modelz", "J. Cole"],
  ["Love Yourz", "J. Cole"],
  ["Apparently", "J. Cole"],
  ["Wet Dreamz", "J. Cole"],
  ["Power Trip", "J. Cole"],
  ["Crooked Smile", "J. Cole"],
  ["Middle Child", "J. Cole"],
  ["4 Your Eyez Only", "J. Cole"],
  ["She Knows", "J. Cole"],
  ["Best Day Ever", "Mac Miller"],
  ["Self Care", "Mac Miller"],
  ["Good News", "Mac Miller"],
  ["Circles", "Mac Miller"],
  ["Blue World", "Mac Miller"],
  ["Come Back to Earth", "Mac Miller"],
  ["2009", "Mac Miller"],
  ["Ladders", "Mac Miller"],
  ["Dang!", "Mac Miller"],
  ["Weekend", "Mac Miller"],
  ["My Favorite Part", "Mac Miller"],
  ["Stay", "Mac Miller"],
  ["ROS", "Mac Miller"],
  ["Congratulations", "Mac Miller"],
  ["Objects in the Mirror", "Mac Miller"],
  ["Youforia", "Mac Miller"],
  ["Surf", "Mac Miller"],
  ["Woods", "Mac Miller"],
  ["Hand Me Downs", "Mac Miller"],
  ["That's on Me", "Mac Miller"],
  ["Hurt Feelings", "Mac Miller"],
  ["What's the Use?", "Mac Miller"],
  ["Sunflower", "Post Malone"],
  ["Circles", "Post Malone"],
  ["Stay", "Post Malone"],
  ["Better Now", "Post Malone"],
  ["Feeling Whitney", "Post Malone"],
  ["I Fall Apart", "Post Malone"],
  ["Congratulations", "Post Malone"],
  ["Chemical", "Post Malone"],
  ["Passionfruit", "Drake"],
  ["Feel No Ways", "Drake"],
  ["Marvins Room", "Drake"],
  ["Hold On, We're Going Home", "Drake"],
  ["From Time", "Drake"],
  ["Take Care", "Drake"],
  ["Do Not Disturb", "Drake"],
  ["Jungle", "Drake"],
  ["Teenage Fever", "Drake"],
  ["After Dark", "Drake"],
  ["EARFQUAKE", "Tyler, The Creator"],
  ["See You Again", "Tyler, The Creator"],
  ["ARE WE STILL FRIENDS?", "Tyler, The Creator"],
  ["GONE, GONE / THANK YOU", "Tyler, The Creator"],
  ["911 / Mr. Lonely", "Tyler, The Creator"],
  ["Boredom", "Tyler, The Creator"],
  ["November", "Tyler, The Creator"],
  ["Glitter", "Tyler, The Creator"],
  ["WUSYANAME", "Tyler, The Creator"],
  ["Sweet / I Thought You Wanted to Dance", "Tyler, The Creator"],
  ["Sunday", "Earl Sweatshirt"],
  ["Chum", "Earl Sweatshirt"],
  ["Dark Red", "Steve Lacy"],
  ["Bad Habit", "Steve Lacy"],
  ["Sunshine", "Steve Lacy"],
  ["Playground", "Steve Lacy"],

  // ---- country / americana ----
  ["Jolene", "Dolly Parton"],
  ["I Will Always Love You", "Dolly Parton"],
  ["9 to 5", "Dolly Parton"],
  ["Coat of Many Colors", "Dolly Parton"],
  ["Ring of Fire", "Johnny Cash"],
  ["I Walk the Line", "Johnny Cash"],
  ["Hurt", "Johnny Cash"],
  ["Folsom Prison Blues", "Johnny Cash"],
  ["Sunday Mornin' Comin' Down", "Johnny Cash"],
  ["Get Rhythm", "Johnny Cash"],
  ["Always on My Mind", "Willie Nelson"],
  ["On the Road Again", "Willie Nelson"],
  ["Blue Eyes Crying in the Rain", "Willie Nelson"],
  ["Crazy", "Patsy Cline"],
  ["Walkin' After Midnight", "Patsy Cline"],
  ["Sweet Dreams", "Patsy Cline"],
  ["I Fall to Pieces", "Patsy Cline"],
  ["Amarillo by Morning", "George Strait"],
  ["The Chair", "George Strait"],
  ["Check Yes or No", "George Strait"],
  ["Friends in Low Places", "Garth Brooks"],
  ["The Dance", "Garth Brooks"],
  ["The River", "Garth Brooks"],
  ["Unanswered Prayers", "Garth Brooks"],
  ["Remember When", "Alan Jackson"],
  ["Drive", "Alan Jackson"],
  ["Livin' on Love", "Alan Jackson"],
  ["Where Were You", "Alan Jackson"],
  ["My Maria", "Brooks & Dunn"],
  ["Neon Moon", "Brooks & Dunn"],
  ["Believe", "Brooks & Dunn"],
  ["I Won't Let Go", "Rascal Flatts"],
  ["Bless the Broken Road", "Rascal Flatts"],
  ["My Wish", "Rascal Flatts"],
  ["What Hurts the Most", "Rascal Flatts"],
  ["Life Is a Highway", "Rascal Flatts"],
  ["I'll Still Be Loving You", "Restless Heart"],
  ["When She Cries", "Restless Heart"],
  ["I Will Not Say Goodbye", "Danny Gokey"],
  ["Tell Your Heart to Beat Again", "Danny Gokey"],
  ["Need You Now", "Lady A"],
  ["Just a Kiss", "Lady A"],
  ["American Honey", "Lady A"],
  ["The House That Built Me", "Miranda Lambert"],
  ["Tin Man", "Miranda Lambert"],
  ["Bluebird", "Miranda Lambert"],
  ["Springsteen", "Eric Church"],
  ["Like Jesus Does", "Eric Church"],
  ["Talladega", "Eric Church"],
  ["Die a Happy Man", "Thomas Rhett"],
  ["Marry Me", "Thomas Rhett"],
  ["Cover Me Up", "Jason Isbell"],
  ["If We Were Vampires", "Jason Isbell"],
  ["24 Frames", "Jason Isbell"],
  ["Traveling Alone", "Jason Isbell"],
  ["Flagship", "Jason Isbell"],
  ["Last of My Kind", "Jason Isbell"],
  ["Something More Than Free", "Jason Isbell"],
  ["Speed Trap Town", "Jason Isbell"],
  ["Elephant", "Jason Isbell"],
  ["Stockholm", "Jason Isbell"],
  ["Colder Weather", "Zac Brown Band"],
  ["Free", "Zac Brown Band"],
  ["Chicken Fried", "Zac Brown Band"],
  ["Highway 20 Ride", "Zac Brown Band"],
  ["Sweet Annie", "Zac Brown Band"],
  ["Something in the Orange", "Zach Bryan"],
  ["Sun to Me", "Zach Bryan"],
  ["Heading South", "Zach Bryan"],
  ["Oklahoma Smokeshow", "Zach Bryan"],
  ["Burn, Burn, Burn", "Zach Bryan"],
  ["I Remember Everything", "Zach Bryan"],
  ["Sandpaper", "Zach Bryan"],
  ["Pink Skies", "Zach Bryan"],
  ["28", "Zach Bryan"],
  ["Dawns", "Zach Bryan"],
  ["The Good I'll Do", "Zach Bryan"],
  ["Tishomingo", "Zach Bryan"],
  ["Fifth of May", "Zach Bryan"],
  ["Blue Eyes Crying in the Rain", "Zach Bryan"],
  ["Tennessee Whiskey", "Chris Stapleton"],
  ["Broken Halos", "Chris Stapleton"],
  ["Starting Over", "Chris Stapleton"],
  ["Fire Away", "Chris Stapleton"],
  ["Millionaire", "Chris Stapleton"],
  ["Traveller", "Chris Stapleton"],
  ["Joy of My Life", "Chris Stapleton"],
  ["You Should Probably Leave", "Chris Stapleton"],
  ["White Horse", "Chris Stapleton"],
  ["Cold", "Chris Stapleton"],
  ["Either Way", "Chris Stapleton"],
  ["Whiskey and You", "Chris Stapleton"],

  // ---- jazz / standards / oldies ----
  ["What a Wonderful World", "Louis Armstrong"],
  ["La Vie en Rose", "Louis Armstrong"],
  ["Dream a Little Dream of Me", "Ella Fitzgerald & Louis Armstrong"],
  ["Summertime", "Ella Fitzgerald"],
  ["Misty", "Ella Fitzgerald"],
  ["Blue Skies", "Ella Fitzgerald"],
  ["Cheek to Cheek", "Ella Fitzgerald"],
  ["My Funny Valentine", "Chet Baker"],
  ["I Fall in Love Too Easily", "Chet Baker"],
  ["But Not for Me", "Chet Baker"],
  ["Time After Time", "Chet Baker"],
  ["Almost Blue", "Chet Baker"],
  ["I Get Along Without You Very Well", "Chet Baker"],
  ["Let's Get Lost", "Chet Baker"],
  ["Everything Happens to Me", "Chet Baker"],
  ["The Very Thought of You", "Nat King Cole"],
  ["Unforgettable", "Nat King Cole"],
  ["Smile", "Nat King Cole"],
  ["L-O-V-E", "Nat King Cole"],
  ["Autumn Leaves", "Nat King Cole"],
  ["Nature Boy", "Nat King Cole"],
  ["Stardust", "Nat King Cole"],
  ["When I Fall in Love", "Nat King Cole"],
  ["Fly Me to the Moon", "Frank Sinatra"],
  ["The Way You Look Tonight", "Frank Sinatra"],
  ["My Way", "Frank Sinatra"],
  ["Come Fly with Me", "Frank Sinatra"],
  ["Moon River", "Frank Sinatra"],
  ["Summer Wind", "Frank Sinatra"],
  ["That's Life", "Frank Sinatra"],
  ["In the Wee Small Hours of the Morning", "Frank Sinatra"],
  ["I've Got You Under My Skin", "Frank Sinatra"],
  ["Strangers in the Night", "Frank Sinatra"],
  ["New York, New York", "Frank Sinatra"],
  ["Feeling Good", "Nina Simone"],
  ["I Put a Spell on You", "Nina Simone"],
  ["Sinnerman", "Nina Simone"],
  ["Wild Is the Wind", "Nina Simone"],
  ["Stars", "Nina Simone"],
  ["Ain't Got No, I Got Life", "Nina Simone"],
  ["My Baby Just Cares for Me", "Nina Simone"],
  ["Lilac Wine", "Nina Simone"],
  ["I'll Be Seeing You", "Billie Holiday"],
  ["Blue Moon", "Billie Holiday"],
  ["The Very Thought of You", "Billie Holiday"],
  ["Easy Living", "Billie Holiday"],
  ["Solitude", "Billie Holiday"],
  ["God Bless the Child", "Billie Holiday"],
  ["Lover Man", "Billie Holiday"],
  ["Georgia on My Mind", "Ray Charles"],
  ["I Can't Stop Loving You", "Ray Charles"],
  ["Hit the Road Jack", "Ray Charles"],
  ["Come Rain or Come Shine", "Ray Charles"],
  ["Beyond the Sea", "Bobby Darin"],
  ["Dream Lover", "Bobby Darin"],
  ["Sea of Love", "Phil Phillips"],
  ["Earth Angel", "The Penguins"],
  ["In the Still of the Night", "The Five Satins"],
  ["Only You", "The Platters"],
  ["The Great Pretender", "The Platters"],
  ["Smoke Gets in Your Eyes", "The Platters"],
  ["Twilight Time", "The Platters"],
  ["Unchained Melody", "The Righteous Brothers"],
  ["You've Lost That Lovin' Feelin'", "The Righteous Brothers"],
  ["Can't Take My Eyes Off You", "Frankie Valli"],
  ["Sherry", "Frankie Valli & The Four Seasons"],
  ["Save the Last Dance for Me", "The Drifters"],
  ["Under the Boardwalk", "The Drifters"],
  ["This Magic Moment", "The Drifters"],
  ["Blue Velvet", "Bobby Vinton"],
  ["Put Your Head on My Shoulder", "Paul Anka"],
  ["Dream", "The Everly Brothers"],
  ["All I Have to Do Is Dream", "The Everly Brothers"],
  ["Bye Bye Love", "The Everly Brothers"],
  ["Oh, Pretty Woman", "Roy Orbison"],
  ["Crying", "Roy Orbison"],
  ["In Dreams", "Roy Orbison"],
  ["Only the Lonely", "Roy Orbison"],
  ["You Got It", "Roy Orbison"],
  ["Can't Help Falling in Love", "Elvis Presley"],
  ["Love Me Tender", "Elvis Presley"],
  ["Always on My Mind", "Elvis Presley"],
  ["Suspicious Minds", "Elvis Presley"],
  ["Burning Love", "Elvis Presley"],
  ["Are You Lonesome Tonight?", "Elvis Presley"],
  ["We'll Meet Again", "Vera Lynn"],
  ["Time to Say Goodbye", "Andrea Bocelli & Sarah Brightman"],
  ["Somewhere Over the Rainbow", "Israel Kamakawiwo'ole"],
  ["What'll I Do", "Nat King Cole"],
  ["Moonlight Serenade", "Glenn Miller"],
  ["Sway", "Dean Martin"],
  ["That's Amore", "Dean Martin"],
  ["Everybody Loves Somebody", "Dean Martin"],
  ["Ain't That a Kick in the Head", "Dean Martin"],
  ["Volare", "Dean Martin"],
  ["Mack the Knife", "Bobby Darin"],
  ["It Had to Be You", "Harry Connick Jr."],
  ["Recipe for Love", "Harry Connick Jr."],

  // ---- soft rock / yacht / 70s-80s gold ----
  ["Africa (Live)", "TOTO"],
  ["How Deep Is Your Love", "Bee Gees"],
  ["To Love Somebody", "Bee Gees"],
  ["More Than a Woman", "Bee Gees"],
  ["Stayin' Alive", "Bee Gees"],
  ["Words", "Bee Gees"],
  ["Sailing", "Christopher Cross"],
  ["Ride Like the Wind", "Christopher Cross"],
  ["What a Fool Believes", "The Doobie Brothers"],
  ["Listen to the Music", "The Doobie Brothers"],
  ["Black Water", "The Doobie Brothers"],
  ["Long Train Runnin'", "The Doobie Brothers"],
  ["Reelin' in the Years", "Steely Dan"],
  ["Dirty Work", "Steely Dan"],
  ["Do It Again", "Steely Dan"],
  ["Peg", "Steely Dan"],
  ["Deacon Blues", "Steely Dan"],
  ["Rikki Don't Lose That Number", "Steely Dan"],
  ["Lowdown", "Boz Scaggs"],
  ["Lido Shuffle", "Boz Scaggs"],
  ["Baker Street", "Gerry Rafferty"],
  ["Right Down the Line", "Gerry Rafferty"],
  ["Year of the Cat", "Al Stewart"],
  ["Time Passages", "Al Stewart"],
  ["Baby Come Back", "Player"],
  ["Brandy (You're a Fine Girl)", "Looking Glass"],
  ["Summer Breeze", "Seals & Crofts"],
  ["Diamond Girl", "Seals & Crofts"],
  ["I'd Really Love to See You Tonight", "England Dan & John Ford Coley"],
  ["Nights Are Forever Without You", "England Dan & John Ford Coley"],
  ["Just Remember I Love You", "Firefall"],
  ["You Are the Woman", "Firefall"],
  ["Dance with Me", "Orleans"],
  ["Still the One", "Orleans"],
  ["Steal Away", "Robbie Dupree"],
  ["Biggest Part of Me", "Ambrosia"],
  ["How Much I Feel", "Ambrosia"],
  ["You're the Only Woman", "Ambrosia"],
  ["Rosanna (Live)", "TOTO"],
  ["I Keep Forgettin'", "Michael McDonald"],
  ["What You Won't Do for Love", "Bobby Caldwell"],
  ["Open Your Eyes", "Bobby Caldwell"],
  ["Heart to Heart", "Kenny Loggins"],
  ["This Is It", "Kenny Loggins"],
  ["Danny's Song (Live)", "Kenny Loggins"],
  ["Return to Pooh Corner", "Kenny Loggins"],
  ["Wichita Lineman", "Glen Campbell"],
  ["Gentle on My Mind", "Glen Campbell"],
  ["By the Time I Get to Phoenix", "Glen Campbell"],
  ["Everybody's Talkin'", "Harry Nilsson"],
  ["Without You", "Harry Nilsson"],
  ["Coconut", "Harry Nilsson"],
  ["Me and My Arrow", "Harry Nilsson"],
  ["Alone Again (Naturally)", "Gilbert O'Sullivan"],
  ["Wildfire", "Michael Martin Murphey"],
  ["Please Come to Boston", "Dave Loggins"],
  ["Shannon", "Henry Gross"],
  ["The Air That I Breathe", "The Hollies"],
  ["Long Cool Woman in a Black Dress", "The Hollies"],
  ["He Ain't Heavy, He's My Brother", "The Hollies"],
  ["Bus Stop", "The Hollies"],
  ["If You Leave Me Now", "Chicago"],
  ["Colour My World", "Chicago"],
  ["Saturday in the Park", "Chicago"],
  ["25 or 6 to 4", "Chicago"],
  ["Hard to Say I'm Sorry", "Chicago"],
  ["You're the Inspiration", "Chicago"],
  ["Wonderful Tonight", "Eric Clapton"],
  ["Tears in Heaven", "Eric Clapton"],
  ["Change the World", "Eric Clapton"],
  ["My Father's Eyes", "Eric Clapton"],
  ["Layla (Acoustic)", "Eric Clapton"],
  ["Let It Grow", "Eric Clapton"],

  // ---- 2010s-2020s indie pop / bedroom ----
  ["Heat Waves", "Glass Animals"],
  ["Gooey", "Glass Animals"],
  ["Youth", "Glass Animals"],
  ["The Other Side of Paradise", "Glass Animals"],
  ["Agnes", "Glass Animals"],
  ["Cold Little Heart", "Michael Kiwanuka"],
  ["Love & Hate", "Michael Kiwanuka"],
  ["Home Again", "Michael Kiwanuka"],
  ["Rule the World", "Michael Kiwanuka"],
  ["I'm Getting Ready", "Michael Kiwanuka"],
  ["Golden", "Harry Styles"],
  ["Watermelon Sugar", "Harry Styles"],
  ["Adore You", "Harry Styles"],
  ["Falling", "Harry Styles"],
  ["Sunflower, Vol. 6", "Harry Styles"],
  ["Canyon Moon", "Harry Styles"],
  ["Fine Line", "Harry Styles"],
  ["Sign of the Times", "Harry Styles"],
  ["Sweet Creature", "Harry Styles"],
  ["Two Ghosts", "Harry Styles"],
  ["As It Was", "Harry Styles"],
  ["Late Night Talking", "Harry Styles"],
  ["Little Freak", "Harry Styles"],
  ["Matilda", "Harry Styles"],
  ["Satellite", "Harry Styles"],
  ["Love of My Life", "Harry Styles"],
  ["august", "Taylor Swift"],
  ["cardigan", "Taylor Swift"],
  ["the 1", "Taylor Swift"],
  ["exile", "Taylor Swift"],
  ["invisible string", "Taylor Swift"],
  ["betty", "Taylor Swift"],
  ["peace", "Taylor Swift"],
  ["this is me trying", "Taylor Swift"],
  ["mirrorball", "Taylor Swift"],
  ["seven", "Taylor Swift"],
  ["willow", "Taylor Swift"],
  ["champagne problems", "Taylor Swift"],
  ["evermore", "Taylor Swift"],
  ["tolerate it", "Taylor Swift"],
  ["marjorie", "Taylor Swift"],
  ["happiness", "Taylor Swift"],
  ["ivy", "Taylor Swift"],
  ["cowboy like me", "Taylor Swift"],
  ["All Too Well", "Taylor Swift"],
  ["Daylight", "Taylor Swift"],
  ["Lover", "Taylor Swift"],
  ["Cornelia Street", "Taylor Swift"],
  ["The Archer", "Taylor Swift"],
  ["Clean", "Taylor Swift"],
  ["Wildest Dreams", "Taylor Swift"],
  ["Style", "Taylor Swift"],
  ["Enchanted", "Taylor Swift"],
  ["Anti-Hero", "Taylor Swift"],
  ["Snow on the Beach", "Taylor Swift"],
  ["Labyrinth", "Taylor Swift"],
  ["Sweet Nothing", "Taylor Swift"],
  ["Mastermind", "Taylor Swift"],
  ["Fortnight", "Taylor Swift"],
  ["loml", "Taylor Swift"],
  ["Peter", "Taylor Swift"],
  ["The Prophecy", "Taylor Swift"],
  ["So Long, London", "Taylor Swift"],
  ["Pink + White (Live)", "Frank Ocean"],
  ["Line Without a Hook", "Ricky Montgomery"],
  ["Mr Loverman", "Ricky Montgomery"],
  ["This Is Home", "Cavetown"],
  ["Lemon Boy", "Cavetown"],
  ["Devil Town", "Cavetown"],
  ["Green", "Cavetown"],
  ["Fool", "Cavetown"],
  ["Home", "Cavetown"],
  ["Juna", "Clairo"],
  ["Sofia", "Clairo"],
  ["Bags", "Clairo"],
  ["Pretty Girl", "Clairo"],
  ["Amoeba", "Clairo"],
  ["Blouse", "Clairo"],
  ["Alewife", "Clairo"],
  ["Sexy to Someone", "Clairo"],
  ["Nomad", "Clairo"],
  ["Terrapin", "Clairo"],
  ["Falling Behind", "Laufey"],
  ["From the Start", "Laufey"],
  ["Valentine", "Laufey"],
  ["Let You Break My Heart Again", "Laufey"],
  ["Promise", "Laufey"],
  ["California and Me", "Laufey"],
  ["Bewitched", "Laufey"],
  ["Dreamer", "Laufey"],
  ["While You Were Sleeping", "Laufey"],
  ["Second Best", "Laufey"],
  ["Goddess", "Laufey"],
  ["Prom Dress", "mxmtoon"],
  ["Falling for U", "Peachy!"],
  ["Death Bed (Coffee for Your Head)", "Powfu"],
  ["Sunday Best", "Surfaces"],
  ["Loving", "Art Deco"],
  ["Affluenza", "Conan Gray"],
  ["Heather", "Conan Gray"],
  ["Maniac", "Conan Gray"],
  ["Astronomy", "Conan Gray"],
  ["Family Line", "Conan Gray"],
  ["Movies", "Conan Gray"],
  ["The Story", "Conan Gray"],
  ["Crush Culture", "Conan Gray"],
  ["Idle Town", "Conan Gray"],
  ["Wish You Were Sober", "Conan Gray"],
  ["People Watching", "Conan Gray"],
  ["Memories", "Conan Gray"],
  ["Summer Child", "Conan Gray"],
  ["Telepath", "Conan Gray"],
  ["Best Friend", "Rex Orange County"],
  ["Loving Is Easy", "Rex Orange County"],
  ["Sunflower", "Rex Orange County"],
  ["Corduroy Dreams", "Rex Orange County"],
  ["Pluto Projector", "Rex Orange County"],
  ["Amazing", "Rex Orange County"],
  ["Untitled", "Rex Orange County"],
  ["Happiness", "Rex Orange County"],
  ["Television / So Far So Good", "Rex Orange County"],
  ["It's Not the Same Anymore", "Rex Orange County"],
  ["Always", "Rex Orange County"],
  ["THE SHADE", "Rex Orange County"],
  ["7 AM", "Rex Orange County"],
  ["Apricot Princess", "Rex Orange County"],
  ["Never Had the Balls", "Rex Orange County"],
  ["Face to Face", "Rex Orange County"],
  ["Belly (The Grass Stains)", "Cavetown"],
  ["Talk", "beabadoobee"],
  ["Coffee", "beabadoobee"],
  ["Glue Song", "beabadoobee"],
  ["The Perfect Pair", "beabadoobee"],
  ["Cologne", "beabadoobee"],
  ["Ceilings", "Lizzy McAlpine"],
  ["Orange Show Speedway", "Lizzy McAlpine"],
  ["All My Ghosts", "Lizzy McAlpine"],
  ["Doomsday", "Lizzy McAlpine"],
  ["Older", "Lizzy McAlpine"],
  ["Pancakes for Dinner", "Lizzy McAlpine"],
  ["You Ruined the 1975", "Lizzy McAlpine"],
  ["Erase Me", "Lizzy McAlpine"],
  ["Motion Sickness", "Phoebe Bridgers"],
  ["Scott Street", "Phoebe Bridgers"],
  ["Funeral", "Phoebe Bridgers"],
  ["Smoke Signals", "Phoebe Bridgers"],
  ["Garden Song", "Phoebe Bridgers"],
  ["Kyoto", "Phoebe Bridgers"],
  ["Punisher", "Phoebe Bridgers"],
  ["Moon Song", "Phoebe Bridgers"],
  ["Savior Complex", "Phoebe Bridgers"],
  ["Graceland Too", "Phoebe Bridgers"],
  ["I Know the End", "Phoebe Bridgers"],
  ["Emily I'm Sorry", "boygenius"],
  ["True Blue", "boygenius"],
  ["Cool About It", "boygenius"],
  ["Not Strong Enough", "boygenius"],
  ["Letter to an Old Poet", "boygenius"],
  ["Night Shift", "Lucy Dacus"],
  ["VBS", "Lucy Dacus"],
  ["Hot & Heavy", "Lucy Dacus"],
  ["Moon & Stars", "Julien Baker"],
  ["Appointments", "Julien Baker"],
  ["Sprained Ankle", "Julien Baker"],
  ["Something", "Julien Baker"],
  ["Francis Forever", "Mitski"],
  ["First Love / Late Spring", "Mitski"],
  ["Nobody", "Mitski"],
  ["Washing Machine Heart", "Mitski"],
  ["Your Best American Girl", "Mitski"],
  ["My Love Mine All Mine", "Mitski"],
  ["I Bet on Losing Dogs", "Mitski"],
  ["The Only Heartbreaker", "Mitski"],
  ["Pink in the Night", "Mitski"],
  ["A Pearl", "Mitski"],
  ["Angel", "Mitski"],

  // ---- electronic / chill ----
  ["Sun Models", "ODESZA"],
  ["A Moment Apart", "ODESZA"],
  ["Line of Sight", "ODESZA"],
  ["Higher Ground", "ODESZA"],
  ["The Last Goodbye", "ODESZA"],
  ["Light of Day", "ODESZA"],
  ["Say My Name", "ODESZA"],
  ["Bloom", "ODESZA"],
  ["It's Only", "ODESZA"],
  ["Kusanagi", "ODESZA"],
  ["Intro", "M83"],
  ["Nightcall", "Kavinsky"],
  ["Instant Crush", "Daft Punk"],
  ["Something About Us", "Daft Punk"],
  ["Digital Love", "Daft Punk"],
  ["Get Lucky", "Daft Punk"],
  ["Touch", "Daft Punk"],
  ["Veridis Quo", "Daft Punk"],
  ["Within", "Daft Punk"],
  ["Strobe", "deadmau5"],
  ["I Remember", "deadmau5 & Kaskade"],
  ["Faded", "ZHU"],
  ["Sun Is Shining", "Bob Marley vs. Funkstar De Luxe"],
  ["Cold Heart", "Elton John & Dua Lipa"],
  ["Levitating", "Dua Lipa"],
  ["Don't Start Now", "Dua Lipa"],
  ["Break My Heart", "Dua Lipa"],
  ["Physical", "Dua Lipa"],
  ["Houdini", "Dua Lipa"],
  ["Illusion", "Dua Lipa"],
  ["Training Season", "Dua Lipa"],
  ["These Walls", "Dua Lipa"],
  ["Wake Me Up", "Avicii"],
  ["Hey Brother", "Avicii"],
  ["The Nights", "Avicii"],
  ["Waiting for Love", "Avicii"],
  ["Without You", "Avicii"],
  ["Lonely Together", "Avicii"],
  ["Stay", "Zedd & Alessia Cara"],
  ["Clarity", "Zedd"],
  ["The Middle", "Zedd, Maren Morris & Grey"],
  ["Roses", "The Chainsmokers"],
  ["Closer", "The Chainsmokers"],
  ["Something Just Like This", "The Chainsmokers & Coldplay"],
  ["Paris", "The Chainsmokers"],
  ["Cold Water", "Major Lazer"],
  ["Lean On", "Major Lazer"],
  ["Where Are Ü Now", "Skrillex & Diplo"],
  ["Shelter", "Porter Robinson & Madeon"],
  ["Language", "Porter Robinson"],
  ["Sea of Voices", "Porter Robinson"],
  ["Goodbye to a World", "Porter Robinson"],
  ["Look at the Sky", "Porter Robinson"],
  ["Everything Goes On", "Porter Robinson"],
  ["Get Your Wish", "Porter Robinson"],
  ["Sunrise", "Norah Jones"],
  ["Come Away with Me", "Norah Jones"],
  ["Don't Know Why", "Norah Jones"],
  ["Turn Me On", "Norah Jones"],
  ["The Nearness of You", "Norah Jones"],

  // ---- more 2020s / misc ----
  ["Good Days", "SZA"],
  ["Snooze", "SZA"],
  ["Kill Bill", "SZA"],
  ["Nobody Gets Me", "SZA"],
  ["The Weekend", "SZA"],
  ["Broken Clocks", "SZA"],
  ["Drew Barrymore", "SZA"],
  ["Garden (Say It Like Dat)", "SZA"],
  ["Normal Girl", "SZA"],
  ["20 Something", "SZA"],
  ["Saturn", "SZA"],
  ["Stay", "The Kid LAROI & Justin Bieber"],
  ["Ghost", "Justin Bieber"],
  ["Peaches", "Justin Bieber"],
  ["Lonely", "Justin Bieber"],
  ["Anyone", "Justin Bieber"],
  ["Holy", "Justin Bieber"],
  ["Off My Face", "Justin Bieber"],
  ["Sorry", "Justin Bieber"],
  ["Love Yourself", "Justin Bieber"],
  ["Company", "Justin Bieber"],
  ["Purpose", "Justin Bieber"],
  ["drivers license", "Olivia Rodrigo"],
  ["deja vu", "Olivia Rodrigo"],
  ["traitor", "Olivia Rodrigo"],
  ["favorite crime", "Olivia Rodrigo"],
  ["happier", "Olivia Rodrigo"],
  ["vampire", "Olivia Rodrigo"],
  ["lacy", "Olivia Rodrigo"],
  ["logical", "Olivia Rodrigo"],
  ["the grudge", "Olivia Rodrigo"],
  ["teenage dream", "Olivia Rodrigo"],
  ["Beautiful Things", "Benson Boone"],
  ["Slow It Down", "Benson Boone"],
  ["Ghost Town", "Benson Boone"],
  ["To Love Someone", "Benson Boone"],
  ["Cry", "Benson Boone"],
  ["Before You", "Benson Boone"],
  ["My Greatest Fear", "Benson Boone"],
  ["Little Runaway", "Benson Boone"],
  ["Empty Bed", "Benson Boone"],
  ["Friend", "Benson Boone"],
  ["Sun Keeps Risin'", "Benson Boone"],
  ["What Was", "Benson Boone"],
  ["Death Wish Love", "Benson Boone"],
  ["Forever and a Day", "Benson Boone"],
  ["Time Is Not on Our Side", "Benson Boone"],
  ["Pretty Slowly", "Benson Boone"],
  ["Better Alone", "Benson Boone"],
  ["Coffee Cake", "Benson Boone"],
  ["Love of Mine", "Benson Boone"],
  ["Fireworks & Rollerblades", "Benson Boone"],
  ["Flowers", "Miley Cyrus"],
  ["The Climb", "Miley Cyrus"],
  ["Wrecking Ball", "Miley Cyrus"],
  ["Malibu", "Miley Cyrus"],
  ["Used to Be Young", "Miley Cyrus"],
  ["Slide Away", "Miley Cyrus"],
  ["Angels Like You", "Miley Cyrus"],
  ["Jaded", "Miley Cyrus"],
  ["Rise", "Andra Day"],
  ["Rise Up", "Andra Day"],
  ["Golden Hour", "JVKE"],
  ["This Is What Falling in Love Feels Like", "JVKE"],
  ["Her", "JVKE"],
  ["Dandelions", "Ruth B."],
  ["Lost Boy", "Ruth B."],
  ["Paper Rings", "Taylor Swift"],
  ["Say You Won't Let Go", "James Arthur"],
  ["Falling Like the Stars", "James Arthur"],
  ["Car's Outside", "James Arthur"],
  ["Train Wreck", "James Arthur"],
  ["Rewrite the Stars", "James Arthur & Anne-Marie"],
  ["A Thousand Years", "Christina Perri"],
  ["Jar of Hearts", "Christina Perri"],
  ["Human", "Christina Perri"],
  ["All of the Stars (Live)", "Ed Sheeran"],
  ["Beige", "Yoke Lore"],
  ["Goodpain", "Yoke Lore"],
  ["Chin Up", "Yoke Lore"],
  ["Fake You", "Yoke Lore"],
  ["Sensitive", "Serena Isioma"],
  ["Fous n'importe où", "Claire Laffut"],
  ["Meet Me at Our Spot", "THE ANXIETY"],
  ["Freaks", "Surf Curse"],
  ["Disco", "Surf Curse"],
  ["Chateau", "Angus & Julia Stone"],
  ["Big Jet Plane", "Angus & Julia Stone"],
  ["Snow", "Angus & Julia Stone"],
  ["Grizzly Bear", "Angus & Julia Stone"],
  ["Just a Boy", "Angus & Julia Stone"],
  ["Santa Monica Dream", "Angus & Julia Stone"],
  ["Draw Your Swords", "Angus & Julia Stone"],
  ["Yellow Brick Road", "Angus & Julia Stone"],
  ["Paper Aeroplane", "Angus & Julia Stone"],
  ["The Wonder of You", "Villagers"],
  ["Nothing Arrived", "Villagers"],
  ["Courage", "Villagers"],
  ["So Simpatico", "Villagers"],
  ["My Lighthouse", "Villagers"],
  ["Wild Horses (Acoustic)", "The Rolling Stones"],
  ["Ophelia (Live)", "The Lumineers"],
  ["Skinny Love", "Birdy"],
  ["People Help the People", "Birdy"],
  ["Wings", "Birdy"],
  ["1901", "Phoenix"],
  ["Lisztomania", "Phoenix"],
  ["Too Young", "Phoenix"],
  ["If I Ever Feel Better", "Phoenix"],
  ["Armistice", "Phoenix"],
  ["Tonight", "Phoenix"],
  ["Walkin' on the Sun", "Smash Mouth"],
  ["All Star", "Smash Mouth"],
  ["I'm a Believer", "Smash Mouth"],
  ["Send Me on My Way", "Rusted Root"],
  ["Banditos", "The Refreshments"],
  ["The Way", "Fastball"],
  ["Out of My Head", "Fastball"],
  ["Fire Escape", "Fastball"],
  ["Steal My Sunshine", "Len"],
  ["Absolutely (Story of a Girl)", "Nine Days"],
  ["Kryptonite", "3 Doors Down"],
  ["Here Without You", "3 Doors Down"],
  ["Be Like That", "3 Doors Down"],
  ["When I'm Gone", "3 Doors Down"],
  ["Wherever You Will Go", "The Calling"],
  ["Drops of Jupiter", "Train"],
  ["Meet Virginia", "Train"],
  ["Calling All Angels", "Train"],
  ["Marry Me", "Train"],
  ["Hey, Soul Sister", "Train"],
  ["Chicken Fried (Live)", "Zac Brown Band"],
  ["Big Green Tractor", "Jason Aldean"],
  ["Fly Over States", "Jason Aldean"],
  ["What a Beautiful Name", "Hillsong Worship"],
  ["Oceans (Where Feet May Fail)", "Hillsong UNITED"],
  ["Reckless Love", "Cory Asbury"],
  ["Way Maker", "Leeland"],
  ["Amazing Grace (My Chains Are Gone)", "Chris Tomlin"],
  ["How Great Is Our God", "Chris Tomlin"],
  ["10,000 Reasons (Bless the Lord)", "Matt Redman"],
  ["Build My Life", "Pat Barrett"],
  ["Gratitude", "Brandon Lake"],
  ["Goodness of God", "Bethel Music"],
  ["House of Gold", "Twenty One Pilots"],
  ["Northern Attitude", "Noah Kahan"],
  ["Stick Season", "Noah Kahan"],
  ["All My Love", "Noah Kahan"],
  ["She Calls Me Back", "Noah Kahan"],
  ["Come Over", "Noah Kahan"],
  ["New Perspective", "Noah Kahan"],
  ["Everywhere, Everything", "Noah Kahan"],
  ["Orange Juice", "Noah Kahan"],
  ["Growing Sideways", "Noah Kahan"],
  ["Halloween", "Noah Kahan"],
  ["Homesick", "Noah Kahan"],
  ["Still", "Noah Kahan"],
  ["The View Between Villages", "Noah Kahan"],
  ["Your Needs, My Needs", "Noah Kahan"],
  ["Dial Drunk", "Noah Kahan"],
  ["Paul Revere", "Noah Kahan"],
  ["No Complaints", "Noah Kahan"],
  ["False Confidence", "Noah Kahan"],
  ["Young Blood", "Noah Kahan"],
  ["Hurt Somebody", "Noah Kahan"],
  ["Mess", "Noah Kahan"],
  ["Carlo's Song", "Noah Kahan"],
  ["Maine", "Noah Kahan"],
  ["Glue Myself Shut", "Noah Kahan"],
  ["Godlight", "Noah Kahan"],
  ["Anyway", "Noah Kahan"],
  ["Pride", "Noah Kahan"],
  ["Strawberry Wine", "Noah Kahan"],
  ["Forever", "Noah Kahan"],
  ["The Great Divide", "Noah Kahan"],
  ["Sarah's Place", "Noah Kahan"],
  ["Water", "Tyla"],
  ["Espresso", "Sabrina Carpenter"],
  ["Please Please Please", "Sabrina Carpenter"],
  ["Nonsense", "Sabrina Carpenter"],
  ["Feather", "Sabrina Carpenter"],
  ["because i liked a boy", "Sabrina Carpenter"],
  ["A Bar Song (Tipsy)", "Shaboozey"],
  ["Texas Hold 'Em", "Beyoncé"],
  ["Lose Control", "Teddy Swims"],
  ["The Door", "Teddy Swims"],
  ["Bed on Fire", "Teddy Swims"],
  ["Some Things I'll Never Know", "Teddy Swims"],
  ["Devil in a Dress", "Teddy Swims"],
  ["Riptide (Live)", "Vance Joy"],
  ["Until I Found You", "Stephen Sanchez"],
  ["Be More", "Stephen Sanchez"],
  ["High", "Stephen Sanchez"],
  ["Evangeline", "Stephen Sanchez"],
  ["I Want You Forever", "Stephen Sanchez"],
  ["Something About Her", "Stephen Sanchez"],
  ["Doin' Time", "Lana Del Rey"],
  ["Video Games", "Lana Del Rey"],
  ["Young and Beautiful", "Lana Del Rey"],
  ["Summertime Sadness", "Lana Del Rey"],
  ["Born to Die", "Lana Del Rey"],
  ["Ride", "Lana Del Rey"],
  ["West Coast", "Lana Del Rey"],
  ["Brooklyn Baby", "Lana Del Rey"],
  ["Mariners Apartment Complex", "Lana Del Rey"],
  ["Venice Bitch", "Lana Del Rey"],
  ["The greatest", "Lana Del Rey"],
  ["Chemtrails Over the Country Club", "Lana Del Rey"],
  ["Arcadia", "Lana Del Rey"],
  ["A&W", "Lana Del Rey"],
  ["Did you know that there's a tunnel under Ocean Blvd", "Lana Del Rey"],
  ["Margaret", "Lana Del Rey"],
  ["Let the Light In", "Lana Del Rey"],
  ["Say Yes to Heaven", "Lana Del Rey"],
];

// de-duplicate on title+artist, keep first occurrence
const seen = new Set();
export const DEMO_LIBRARY = SONGS.filter(([title, artist]) => {
  const key = (title + "::" + artist).toLowerCase();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
}).map(([title, artist]) => ({ title, artist, uri: null }));
