// A stand-in "Liked Songs" library so anyone can try the poem composer
// without connecting Spotify. Titles only get used as poem lines here;
// demo mode can't save to a real account.

export const DEMO_LIBRARY = [
  ["Here Comes the Sun", "The Beatles"],
  ["I Will Follow You into the Dark", "Death Cab for Cutie"],
  ["Sometimes", "My Bloody Valentine"],
  ["When You Were Young", "The Killers"],
  ["We Found Love", "Rihanna"],
  ["Don't Look Back in Anger", "Oasis"],
  ["And It Stoned Me", "Van Morrison"],
  ["But Not for Me", "Chet Baker"],
  ["So Far Away", "Carole King"],
  ["Why Do Fools Fall in Love", "Frankie Lymon"],
  ["What a Wonderful World", "Louis Armstrong"],
  ["Where Is My Mind?", "Pixies"],
  ["How Deep Is Your Love", "Bee Gees"],
  ["Will You Love Me Tomorrow", "The Shirelles"],
  ["Home", "Edward Sharpe & The Magnetic Zeros"],
  ["Goodbye Yellow Brick Road", "Elton John"],
  ["The Night We Met", "Lord Huron"],
  ["Midnight City", "M83"],
  ["Dancing in the Moonlight", "King Harvest"],
  ["Stars", "Nina Simone"],
  ["Dreams", "Fleetwood Mac"],
  ["Morning Has Broken", "Cat Stevens"],
  ["Waking Up Slow", "Gabrielle Aplin"],
  ["Brand New Day", "Sting"],
  ["Summertime", "Ella Fitzgerald"],
  ["July", "Noah Cyrus"],
  ["August", "Taylor Swift"],
  ["Golden Hour", "JVKE"],
  ["Heat Waves", "Glass Animals"],
  ["Cold Little Heart", "Michael Kiwanuka"],
  ["Sweater Weather", "The Neighbourhood"],
  ["Autumn Leaves", "Nat King Cole"],
  ["A Hazy Shade of Winter", "Simon & Garfunkel"],
  ["Take Me Home, Country Roads", "John Denver"],
  ["Homeward Bound", "Simon & Garfunkel"],
  ["Our House", "Crosby, Stills, Nash & Young"],
  ["Fast Car", "Tracy Chapman"],
  ["Drive", "Incubus"],
  ["On the Road Again", "Willie Nelson"],
  ["Ramble On", "Led Zeppelin"],
  ["Run", "Snow Patrol"],
  ["Walking on Sunshine", "Katrina & The Waves"],
  ["Riders on the Storm", "The Doors"],
  ["The River", "Bruce Springsteen"],
  ["Ocean Eyes", "Billie Eilish"],
  ["Only the Ocean", "Jack Johnson"],
  ["Singin' in the Rain", "Gene Kelly"],
  ["Have You Ever Seen the Rain?", "Creedence Clearwater Revival"],
  ["Waves", "Dean Lewis"],
  ["Swim Good", "Frank Ocean"],
  ["Blue Skies", "Ella Fitzgerald"],
  ["Fly Me to the Moon", "Frank Sinatra"],
  ["Learning to Fly", "Tom Petty"],
  ["Free Bird", "Lynyrd Skynyrd"],
  ["Blackbird", "The Beatles"],
  ["Three Little Birds", "Bob Marley & The Wailers"],
  ["The Wind", "Cat Stevens"],
  ["Dust in the Wind", "Kansas"],
  ["Ring of Fire", "Johnny Cash"],
  ["Light My Fire", "The Doors"],
  ["Burning Love", "Elvis Presley"],
  ["Smoke Gets in Your Eyes", "The Platters"],
  ["Time After Time", "Cyndi Lauper"],
  ["Yesterday", "The Beatles"],
  ["Tomorrow Never Knows", "The Beatles"],
  ["Forever Young", "Alphaville"],
  ["Always", "Bon Jovi"],
  ["Never Gonna Give You Up", "Rick Astley"],
  ["Wait for It", "Leslie Odom Jr."],
  ["Someday", "The Strokes"],
  ["Memories", "Maroon 5"],
  ["Remember When", "Alan Jackson"],
  ["The Way We Were", "Barbra Streisand"],
  ["Landslide", "Fleetwood Mac"],
  ["Both Sides Now", "Joni Mitchell"],
  ["Hope of Deliverance", "Paul McCartney"],
  ["I Can See Clearly Now", "Johnny Nash"],
  ["Rise Up", "Andra Day"],
  ["Shine On You Crazy Diamond", "Pink Floyd"],
  ["Better Days", "OneRepublic"],
  ["Dream On", "Aerosmith"],
  ["Dancing Queen", "ABBA"],
  ["I Wanna Dance with Somebody", "Whitney Houston"],
  ["Shut Up and Dance", "WALK THE MOON"],
  ["Sing", "Ed Sheeran"],
  ["Rhythm of the Night", "DeBarge"],
  ["Mother", "John Lennon"],
  ["Father and Son", "Cat Stevens"],
  ["Sister Golden Hair", "America"],
  ["Hey Brother", "Avicii"],
  ["Sweet Child o' Mine", "Guns N' Roses"],
  ["Lean on Me", "Bill Withers"],
  ["With a Little Help from My Friends", "Joe Cocker"],
  ["You've Got a Friend in Me", "Randy Newman"],
  ["Count on Me", "Bruno Mars"],
  ["Stand by Me", "Ben E. King"],
  ["9 to 5", "Dolly Parton"],
  ["Money", "Pink Floyd"],
  ["Working Class Hero", "John Lennon"],
  ["Peaceful Easy Feeling", "Eagles"],
  ["The Sound of Silence", "Simon & Garfunkel"],
  ["Breathe", "Pink Floyd"],
  ["Easy", "Commodores"],
  ["Slow Down", "Chase Atlantic"],
  ["Tears in Heaven", "Eric Clapton"],
  ["Everybody Hurts", "R.E.M."],
  ["Hurt", "Johnny Cash"],
  ["Ain't No Sunshine", "Bill Withers"],
  ["Lonely", "Justin Bieber"],
  ["Happy", "Pharrell Williams"],
  ["Good Vibrations", "The Beach Boys"],
  ["Beautiful Day", "U2"],
  ["Lovely Day", "Bill Withers"],
  ["Celebration", "Kool & The Gang"],
  ["Smile", "Nat King Cole"],
  ["Alive", "Pearl Jam"],
  ["Say Goodbye", "Dave Matthews Band"],
  ["The End", "The Beatles"],
  ["Closing Time", "Semisonic"],
  ["Leaving on a Jet Plane", "John Denver"],
  ["Already Gone", "Eagles"],
  ["See You Again", "Wiz Khalifa"],
  ["Till I See You Again", "Nick Wilson"],
  ["Miles Away", "Madonna"],
  ["From a Distance", "Bette Midler"],
  ["Across the Universe", "The Beatles"],
  ["Brave", "Sara Bareilles"],
  ["Fear of the Dark", "Iron Maiden"],
  ["Stronger", "Kelly Clarkson"],
  ["Fight Song", "Rachel Platten"],
  ["The Climb", "Miley Cyrus"],
  ["Eye of the Tiger", "Survivor"],
  ["Don't Stop Believin'", "Journey"],
  ["Beginning", "Joe Hisaishi"],
  ["A New Day Has Come", "Celine Dion"],
  ["Feeling Good", "Nina Simone"],
  ["My Way", "Frank Sinatra"],
  ["Let It Be", "The Beatles"],
  ["I Lived", "OneRepublic"],
  ["Time to Say Goodbye", "Andrea Bocelli"],
  ["Carry Me Home", "Hey Rosetta!"],
  ["I'll Be Seeing You", "Billie Holiday"],
  ["We'll Meet Again", "Vera Lynn"],
  ["Into the Mystic", "Van Morrison"],
  ["Wish You Were Here", "Pink Floyd"],
  ["Vienna", "Billy Joel"],
  ["Landslide", "The Chicks"],
  ["Rivers and Roads", "The Head and the Heart"],
  ["This Must Be the Place (Naive Melody)", "Talking Heads"],
  ["Such Great Heights", "The Postal Service"],
  ["First Day of My Life", "Bright Eyes"],
  ["Bloom", "The Paper Kites"],
  ["Holocene", "Bon Iver"],
  ["Skinny Love", "Bon Iver"],
  ["Re: Stacks", "Bon Iver"],
  ["Your Song", "Elton John"],
  ["Songbird", "Fleetwood Mac"],
  ["Thank You", "Led Zeppelin"],
].map(([title, artist]) => ({ title, artist, uri: null }));
